"""BugCluster data model for semantic bug clustering."""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


class BugCluster(BaseModel):
    """
    Semantic bug cluster from vector similarity clustering.

    Represents a group of bugs with similar error semantics,
    generated by LLM embeddings and LanceDB vector search.
    """
    # Cluster metadata
    cluster_id: str = Field(..., description="Unique cluster identifier")
    theme: str = Field(..., description="LLM-generated theme summarizing cluster")
    size: int = Field(..., description="Number of bugs in cluster", ge=2)

    # Similarity metrics
    similarity_scores: List[float] = Field(..., description="Cosine similarity scores for cluster members")
    avg_similarity: float = Field(..., description="Average similarity in cluster", ge=0.0, le=1.0)

    # Bug references
    bug_ids: List[str] = Field(..., description="Bug report IDs in cluster")
    bug_reports: List[str] = Field(..., description="Test names/descriptions for cluster members")

    # Representative bug (most central)
    representative_bug: str = Field(..., description="ID of most representative bug")

    # Metadata
    discovery_methods: List[str] = Field(..., description="Discovery methods in cluster")
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Optional cluster statistics
    severity_distribution: Optional[Dict[str, int]] = Field(None, description="Count by severity level")
    platform_distribution: Optional[Dict[str, int]] = Field(None, description="Count by platform")

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
