"""FuzzingStrategy data model for AI-generated fuzzing strategies."""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum


class BusinessImpact(str, Enum):
    """Business impact tiers from coverage gap analysis."""
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class FuzzingStrategy(BaseModel):
    """
    AI-generated fuzzing strategy for coverage-aware testing.

    Generated by FuzzingStrategyGenerator from coverage gap analysis.
    Contains target endpoint, suggested inputs, and rationale for strategy.
    """
    # Coverage gap context
    file_path: str = Field(..., description="File with coverage gap")
    missing_lines: List[int] = Field(..., description="Uncovered line numbers")
    business_impact: BusinessImpact = Field(..., description="Business impact tier")
    priority_score: float = Field(..., description="Priority score from gap analysis")

    # Fuzzing strategy
    target_endpoint: str = Field(..., description="API endpoint to fuzz")
    test_file: str = Field(..., description="Fuzzing test file path")
    fuzz_target: str = Field(..., description="Parameter/function to fuzz")
    suggested_inputs: List[str] = Field(..., description="Edge cases to test")
    iterations: int = Field(..., description="Number of fuzzing iterations", ge=1000, le=20000)
    rationale: str = Field(..., description="Why this strategy covers the gap")

    # Validation metadata
    confidence_score: float = Field(..., description="LLM confidence (0.0-1.0)", ge=0.0, le=1.0)
    validated: bool = Field(default=False, description="Strategy validated against codebase")

    class Config:
        use_enum_values = True
