"""InvariantSuggestion data model for AI-generated property test invariants."""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum


class Criticality(str, Enum):
    """Invariant criticality levels."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    STANDARD = "STANDARD"
    LOW = "LOW"


class InvariantSuggestion(BaseModel):
    """
    AI-generated property test invariant suggestion.

    Generated by InvariantGenerator from code analysis.
    Contains formal specification, Hypothesis strategy, and test skeleton.
    """
    # Identification
    invariant_name: str = Field(..., description="Short descriptive name")
    function_name: str = Field(..., description="Target function to test")

    # Invariant specification
    hypothesis: str = Field(..., description="Natural language invariant statement")
    formal_specification: str = Field(..., description="Mathematical/logical specification")
    rationale: str = Field(..., description="Why this invariant matters")

    # Hypothesis integration
    hypothesis_strategy: str = Field(..., description="Hypothesis test data generation strategy")
    criticality: Criticality = Field(..., description="Test criticality level")

    # Test generation
    test_skeleton: str = Field(..., description="Property test code skeleton")
    suggested_examples: int = Field(..., description="Suggested max_examples setting", ge=10, le=1000)

    # Validation metadata
    is_testable: bool = Field(default=False, description="Invariant is testable with Hypothesis")
    validation_errors: List[str] = Field(default_factory=list, description="Validation failures")

    # Code context
    file_path: Optional[str] = Field(None, description="Source file path")
    line_numbers: Optional[List[int]] = Field(None, description="Relevant line numbers")

    class Config:
        use_enum_values = True
