from datetime import datetime, timedelta
import logging
import os
import random
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

class MockModeManager:
    """
    Manages mock data generation and state for integrations running without credentials.
    """
    
    def __init__(self):
        # Disabled by default in production; set MOCK_MODE_ENABLED=true to enable
        self.enabled = os.getenv("MOCK_MODE_ENABLED", "false").lower() == "true"
        
    def is_mock_mode(self, service_name: str, has_credentials: bool) -> bool:
        """
        Determine if a service should run in mock mode.
        Returns True if global mock mode is enabled AND credentials are missing.
        """
        if not self.enabled:
            return False
        return not has_credentials

    def get_mock_data(self, service_name: str, resource_type: str, count: int = 5) -> Any:
        """
        Generate mock data for a specific service and resource.
        """
        generator = getattr(self, f"_generate_{service_name}_{resource_type}", None)
        if generator:
            return generator(count)
        
        logger.warning(f"No mock generator found for {service_name}/{resource_type}")
        return []

    # --- Salesforce Generators ---
    
    def _generate_salesforce_accounts(self, count: int) -> List[Dict[str, Any]]:
        industries = ["Technology", "Finance", "Healthcare", "Retail", "Manufacturing"]
        accounts = []
        for i in range(count):
            accounts.append({
                "Id": f"001{random.randint(100000000000, 999999999999)}AAA",
                "Name": f"Mock Company {i+1}",
                "Type": "Customer - Direct",
                "Industry": random.choice(industries),
                "Phone": f"(555) 010-{1000+i}",
                "Website": f"https://www.mockcompany{i+1}.com",
                "Description": "This is a mock account generated by ATOM Mock Mode."
            })
        return accounts

    def _generate_salesforce_contacts(self, count: int) -> List[Dict[str, Any]]:
        contacts = []
        for i in range(count):
            contacts.append({
                "Id": f"003{random.randint(100000000000, 999999999999)}AAA",
                "FirstName": f"MockUser{i+1}",
                "LastName": "Doe",
                "Email": f"user{i+1}@mockcompany.com",
                "Phone": f"(555) 020-{2000+i}",
                "Title": "Manager",
                "AccountId": f"001{random.randint(100000000000, 999999999999)}AAA"
            })
        return contacts
        
    def _generate_salesforce_opportunities(self, count: int) -> List[Dict[str, Any]]:
        stages = ["Prospecting", "Qualification", "Needs Analysis", "Value Proposition", "Closed Won", "Closed Lost"]
        opportunities = []
        for i in range(count):
            opportunities.append({
                "Id": f"006{random.randint(100000000000, 999999999999)}AAA",
                "Name": f"Mock Opportunity {i+1}",
                "StageName": random.choice(stages),
                "Amount": random.randint(1000, 50000),
                "CloseDate": (datetime.now() + timedelta(days=random.randint(10, 90))).strftime("%Y-%m-%d"),
                "AccountId": f"001{random.randint(100000000000, 999999999999)}AAA"
            })
        return opportunities

    # --- HubSpot Generators ---

    def _generate_hubspot_contacts(self, count: int) -> List[Dict[str, Any]]:
        contacts = []
        for i in range(count):
            contacts.append({
                "id": str(random.randint(100000, 999999)),
                "properties": {
                    "firstname": f"HubSpotUser{i+1}",
                    "lastname": "Smith",
                    "email": f"hubspot{i+1}@example.com",
                    "company": f"HubSpot Mock Co {i+1}",
                    "phone": f"555-030-{3000+i}"
                },
                "createdAt": datetime.now().isoformat(),
                "updatedAt": datetime.now().isoformat(),
                "archived": False
            })
        return contacts
        
    def _generate_hubspot_deals(self, count: int) -> List[Dict[str, Any]]:
        stages = ["appointmentscheduled", "qualifiedtobuy", "presentationscheduled", "decisionmakerbought", "contractsent", "closedwon", "closedlost"]
        deals = []
        for i in range(count):
            deals.append({
                "id": str(random.randint(100000, 999999)),
                "properties": {
                    "dealname": f"Mock Deal {i+1}",
                    "amount": str(random.randint(5000, 100000)),
                    "dealstage": random.choice(stages),
                    "closedate": (datetime.now() + timedelta(days=random.randint(15, 60))).isoformat()
                },
                "createdAt": datetime.now().isoformat(),
                "updatedAt": datetime.now().isoformat(),
                "archived": False
            })
        return deals

    # --- Zoom Generators ---

    def _generate_zoom_meetings(self, count: int) -> List[Dict[str, Any]]:
        meetings = []
        types = [1, 2, 3, 8] # Instant, Scheduled, Recurring...
        for i in range(count):
            start_time = datetime.now() + timedelta(days=random.randint(0, 7), hours=random.randint(0, 23))
            meetings.append({
                "id": random.randint(8000000000, 9999999999),
                "topic": f"Mock Zoom Meeting {i+1}",
                "type": random.choice(types),
                "start_time": start_time.strftime("%Y-%m-%dT%H:%M:%SZ"),
                "duration": random.choice([30, 45, 60]),
                "timezone": "America/New_York",
                "join_url": f"https://zoom.us/j/mock{i+1}",
                "created_at": datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
            })
        return meetings

# Global instance
mock_mode_manager = MockModeManager()

def get_mock_mode_manager() -> MockModeManager:
    return mock_mode_manager
