@echo off
REM Atom Personal Edition - Native Installation Script for Windows
REM This script automates the native installation process
REM Run with: install-native.bat

echo ╔════════════════════════════════════════════════════════════╗
echo ║  Atom Personal Edition - Native Installation              ║
echo ║  AI Automation Platform on Your Local Computer            ║
echo ╚════════════════════════════════════════════════════════════╝
echo.

REM Check prerequisites
echo 🔍 Checking prerequisites...
echo.

REM Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo ❌ Python 3 is not installed. Please install Python 3.11 or higher.
    echo    Download from: https://www.python.org/downloads/
    pause
    exit /b 1
)

for /f "tokens=2" %%i in ('python --version') do set PYTHON_VERSION=%%i
echo ✅ Python found: %PYTHON_VERSION%

REM Check Node.js
node --version >nul 2>&1
if errorlevel 1 (
    echo ❌ Node.js is not installed. Please install Node.js 18 or higher.
    echo    Download from: https://nodejs.org/
    pause
    exit /b 1
)

for /f "tokens=1" %%i in ('node --version') do set NODE_VERSION=%%i
echo ✅ Node.js found: %NODE_VERSION%

REM Check npm
npm --version >nul 2>&1
if errorlevel 1 (
    echo ❌ npm is not installed.
    pause
    exit /b 1
)

for /f "tokens=1" %%i in ('npm --version') do set NPM_VERSION=%%i
echo ✅ npm found: %NPM_VERSION%

REM Check Git
git --version >nul 2>&1
if errorlevel 1 (
    echo ❌ Git is not installed. Please install Git.
    echo    Download from: https://git-scm.com/download/win
    pause
    exit /b 1
)

for /f "tokens=3" %%i in ('git --version') do set GIT_VERSION=%%i
echo ✅ Git found: %GIT_VERSION%

echo.
echo ✅ All prerequisites satisfied!
echo.

REM Backend setup
echo 📦 Setting up backend...
cd backend

REM Create virtual environment
if not exist "venv" (
    echo Creating Python virtual environment...
    python -m venv venv
)

REM Activate virtual environment
echo Activating virtual environment...
call venv\Scripts\activate.bat

REM Upgrade pip
echo Upgrading pip...
python -m pip install --upgrade pip --quiet

REM Install dependencies
echo Installing Python dependencies...
pip install -r requirements.txt --quiet

echo ✅ Backend setup complete!
echo.

REM Frontend setup
echo 📦 Setting up frontend...
cd ..\frontend-nextjs

REM Install dependencies
if not exist "node_modules" (
    echo Installing Node.js dependencies...
    call npm install --silent
)

echo ✅ Frontend setup complete!
echo.

REM Environment configuration
echo ⚙️  Configuring environment...
cd ..

if not exist ".env" (
    if exist ".env.personal" (
        echo Copying .env.personal to .env...
        copy .env.personal .env >nul
    ) else (
        echo Creating .env file...
        (
            echo # Atom Personal Edition - Environment Configuration
            echo # Generated by install-native.bat
            echo.
            echo # AI Provider API Keys ^(REQUIRED - at least one^)
            echo OPENAI_API_KEY=
            echo ANTHROPIC_API_KEY=
            echo.
            echo # Encryption Keys ^(REQUIRED - generate with: python -c "import secrets; print(secrets.token_urlsafe^(32^)^)"^)
            echo BYOK_ENCRYPTION_KEY=
            echo JWT_SECRET_KEY=
            echo.
            echo # Database paths
            echo SQLITE_PATH=./data/atom.db
            echo LANCEDB_PATH=./data/lancedb
            echo.
            echo # Environment
            echo ENVIRONMENT=development
            echo LOG_LEVEL=INFO
        ) > .env
    )
)

REM Generate encryption keys
echo.
echo 🔐 Generating encryption keys...
python -c "import secrets; print(secrets.token_urlsafe(32))" > .key1.tmp
python -c "import secrets; print(secrets.token_urlsafe(32))" > .key2.tmp

set /p KEY1=<.key1.tmp
set /p KEY2=<.key2.tmp

echo Updating .env with encryption keys...
powershell -Command "(gc .env) -replace 'BYOK_ENCRYPTION_KEY=.*', 'BYOK_ENCRYPTION_KEY=%KEY1%' | Out-File -encoding ASCII .env"
powershell -Command "(gc .env) -replace 'JWT_SECRET_KEY=.*', 'JWT_SECRET_KEY=%KEY2%' | Out-File -encoding ASCII .env"

del .key1.tmp
del .key2.tmp

echo ✅ Encryption keys generated and configured
echo.

REM Create data directory
echo 📁 Creating data directory...
if not exist "data" mkdir data
echo ✅ Data directory created: .\data
echo.

REM Run database migrations
echo 🗄️  Running database migrations...
cd backend
call venv\Scripts\activate.bat
alembic upgrade head
echo ✅ Database migrations complete
echo.

cd ..

REM Summary
echo ╔════════════════════════════════════════════════════════════╗
echo ║  ✅ Installation Complete!                                  ║
echo ╚════════════════════════════════════════════════════════════╝
echo.
echo 📝 Next Steps:
echo.
echo 1. Add your AI provider API keys to .env:
echo    notepad .env
echo.
echo    Set at least one of:
echo    - OPENAI_API_KEY=sk-your-key-here
echo    - ANTHROPIC_API_KEY=sk-ant-your-key-here
echo.
echo 2. Start Atom:
echo.
echo    Terminal 1 ^(Backend^):
echo    cd backend
echo    venv\Scripts\activate
echo    python -m uvicorn main_api_app:app --host 0.0.0.0 --port 8000 --reload
echo.
echo    Terminal 2 ^(Frontend^):
echo    cd frontend-nextjs
echo    npm run dev
echo.
echo 3. Access Atom:
echo    🌐 Frontend: http://localhost:3000
echo    🔌 Backend API: http://localhost:8000
echo    📚 API Docs: http://localhost:8000/docs
echo.
echo 📚 Documentation:
echo    - Personal Edition Guide: docs\PERSONAL_EDITION.md
echo    - Native Setup Guide: docs\NATIVE_SETUP.md
echo    - Full Documentation: docs\README.md
echo.
echo 🚀 Happy automating!
echo.

pause
