"""
Factory for CanvasAudit model.

Updated for current schema (Phase 199):
- canvas_id (foreign key to Canvas)
- tenant_id (foreign key to Tenant)
- action_type (e.g., "form_submit", "canvas_close")
- user_id, agent_id (optional)
- episode_id (optional)
- details_json (optional)
- created_at (auto-generated)
"""

import factory
from factory import fuzzy
from datetime import timedelta
from tests.factories.base import BaseFactory
from core.models import CanvasAudit


class CanvasAuditFactory(BaseFactory):
    """Factory for creating CanvasAudit instances."""

    class Meta:
        model = CanvasAudit

    # Required fields
    id = factory.Faker('uuid4')
    canvas_id = factory.Faker('uuid4')
    tenant_id = factory.Faker('uuid4')
    action_type = fuzzy.FuzzyChoice(['form_submit', 'canvas_close', 'artifact_modify', 'agent_action', 'present'])

    # Optional fields
    agent_id = factory.Faker('uuid4')
    user_id = factory.Faker('uuid4')
    episode_id = factory.Faker('uuid4')

    # Action details (JSON for flexibility)
    details_json = factory.LazyFunction(lambda: {"data": "test"})

    # Timing (auto-generated by DB, but can be overridden for testing)
    created_at = factory.Faker('date_time_this_year')
