"""Evidence-grounding contract (core/evidence_grounding.py) and its wiring.

Live incident (2026-09-02, Mark Kellam canvas): the instruction "confirm
480V 3-phase specs" (internal guidance mail) was regenerated by the drafting
turn as an assertion — "the machines we discussed are available in 480V
3-phase configuration" — with zero supporting evidence. Conversation is not
evidence: when a claim can't be grounded, the reply must take the negative
path (say it's unverified) or the middle path (confirmation-in-progress
wording that asserts nothing).
"""

from __future__ import annotations

import inspect

from core.evidence_grounding import (
    CANVAS_ARTIFACT_GROUNDING_RULE,
    EVIDENCE_GROUNDING_RULE,
    asserts_unverified_confirmation,
)


# ───────────────── confirm→assert detector ─────────────────

def test_detector_fires_on_the_live_incident():
    instruction = (
        "generate the draft — the response should confirm 480V 3 phase "
        "availability for the machines"
    )
    draft = (
        "Hi Mark,\n\nYes, the machines we discussed are available in 480V "
        "3-phase configuration."
    )
    assert asserts_unverified_confirmation(instruction, draft)


def test_detector_fires_on_assertion_variants():
    instruction = "draft a reply confirming the voltage specs"
    assert asserts_unverified_confirmation(
        instruction, "Good news: the unit is available in 480V configuration.")
    assert asserts_unverified_confirmation(
        instruction, "This has been confirmed with the manufacturer.")
    assert asserts_unverified_confirmation(
        instruction, "The machines are compatible with your power supply.")


def test_detector_stays_silent_on_middle_path():
    """The required fix — confirmation-in-progress wording asserts nothing."""
    instruction = "draft a reply confirming the voltage specs"
    middle = (
        "Hi Mark,\n\nWe are confirming 480V 3-phase availability and will "
        "follow up with the detailed specs for your machines."
    )
    assert not asserts_unverified_confirmation(instruction, middle)


def test_detector_stays_silent_on_ask_for_info_middle_path():
    """Asking for the missing information is the other middle path — a
    question makes no claim in either direction, even when it contains an
    assertion-marker phrase like "is available"."""
    instruction = "draft a reply confirming the voltage specs"
    ask = (
        "Hi Mark,\n\nTo make sure we recommend the right machine, could you "
        "share the spec sheets so we can confirm whether the units are "
        "available in 480V 3-phase configuration?"
    )
    assert not asserts_unverified_confirmation(instruction, ask)
    # mixed draft: declarative claim + questions still trips — the live
    # incident looked exactly like this
    mixed = (
        "Hi Mark,\n\nYes, the machines we discussed are available in 480V "
        "3-phase configuration. Could you confirm the material you cut?"
    )
    assert asserts_unverified_confirmation(instruction, mixed)


def test_detector_stays_silent_on_negative_path():
    instruction = "draft a reply confirming the voltage specs"
    negative = (
        "Hi Mark,\n\nI can't confirm the 480V 3-phase configuration from "
        "the data available — could you share the machine spec sheets?"
    )
    assert not asserts_unverified_confirmation(instruction, negative)


def test_detector_requires_a_confirm_instruction():
    # No confirm/verify ask in the instruction → an availability statement
    # is just an answer (grounded or not is the model's burden, not this
    # detector's).
    assert not asserts_unverified_confirmation(
        "what machines do you have", "The LCP8080 is available in 480V.")


def test_detector_ignores_empty_inputs():
    assert not asserts_unverified_confirmation("", "The machines are available.")
    assert not asserts_unverified_confirmation("confirm the specs", "")


# ───────────────── prompt wiring ─────────────────

def test_grounding_rule_is_in_both_orchestrator_prompts():
    from integrations import chat_orchestrator as co

    src = inspect.getsource(co.ChatOrchestrator._get_qwen_response)
    # platform prompt + hire-persona prompt
    assert src.count("EVIDENCE_GROUNDING_RULE") >= 2
    # confirm→assert guard wired on BOTH reply paths
    assert src.count("asserts_unverified_confirmation") >= 4  # 2 checks + 2 verdict checks


def test_grounding_rule_is_in_the_canvas_editor_prompt():
    from core import chat_canvas_editor as cce

    assert "CANVAS_ARTIFACT_GROUNDING_RULE" in inspect.getsource(cce)
    assert "EVIDENCE GROUNDING" in cce._EDITOR_SYSTEM
    assert "confirmation-in-progress" in cce._EDITOR_SYSTEM


def test_rules_state_the_negative_and_middle_paths():
    assert "Negative path" in EVIDENCE_GROUNDING_RULE
    assert "Middle path" in EVIDENCE_GROUNDING_RULE
    assert "conversation" in EVIDENCE_GROUNDING_RULE.lower()
    # the middle path has TWO forms: confirmation-in-progress wording and
    # asking for the missing information (a question asserts nothing)
    assert "ask for the missing information" in EVIDENCE_GROUNDING_RULE
    assert "no claim in either direction" in EVIDENCE_GROUNDING_RULE
    assert "Never upgrade an instruction to verify" in EVIDENCE_GROUNDING_RULE
    assert "Never upgrade an instruction to verify" in CANVAS_ARTIFACT_GROUNDING_RULE
    assert "Asking the reader FOR the missing detail" in CANVAS_ARTIFACT_GROUNDING_RULE
    # the confirm→assert regeneration correction offers both forms too
    from integrations import chat_orchestrator as co
    qwen_src = inspect.getsource(co.ChatOrchestrator._get_qwen_response)
    assert qwen_src.count("ask for the missing information") >= 2


# ───────────────── canvas provenance wiring ─────────────────

def test_provenance_reaches_editor_and_conversational_paths():
    import inspect

    from integrations import chat_orchestrator as co

    # editor path: plan_canvas_edit takes provenance, orchestrator passes it
    from core import chat_canvas_editor as cce
    assert "provenance" in inspect.signature(cce.plan_canvas_edit).parameters
    edit_src = inspect.getsource(co.ChatOrchestrator._try_canvas_edit)
    assert "provenance=provenance" in edit_src

    # conversational path: _get_qwen_response takes it and renders the block
    qwen_src = inspect.getsource(co.ChatOrchestrator._get_qwen_response)
    assert "canvas_provenance" in inspect.signature(
        co.ChatOrchestrator._get_qwen_response).parameters
    assert "CANVAS ORIGIN" in qwen_src

    # chat route hydrates it from the create-audit row
    from integrations import chat_routes as cr
    route_src = inspect.getsource(cr)
    assert "canvas_provenance" in inspect.getsource(cr.send_chat_message)
    assert "_canvas_provenance_context" in route_src
