/**
 * ATOM Integration Registry
 * Central registry for all ATOM integrations
 */

import {
  INTEGRATION_CATEGORY_STORAGE,
  INTEGRATION_CATEGORY_COMMUNICATION,
  INTEGRATION_CATEGORY_PRODUCTIVITY,
  INTEGRATION_CATEGORY_DEVELOPMENT,
  INTEGRATION_CATEGORY_COLLABORATION,
  INTEGRATION_CATEGORY_MARKETING,
  INTEGRATION_CATEGORY_CUSTOMER_SERVICE
} from './constants';

// Integration Registry
export const ATOM_INTEGRATIONS = [
  // File Storage Integrations
  {
    id: 'box',
    name: 'Box',
    description: 'Secure file storage and collaboration platform',
    category: INTEGRATION_CATEGORY_STORAGE,
    platform: 'web',
    status: 'complete',
    features: [
      'file_discovery',
      'real_time_sync',
      'metadata_extraction',
      'batch_processing',
      'preview_generation'
    ],
    oauth: {
      provider: 'box',
      scopes: ['read', 'write', 'manage'],
      flow: 'oauth2'
    },
    webhooks: [
      'file.created',
      'file.updated',
      'file.deleted',
      'folder.created',
      'folder.updated'
    ],
    limits: {
      max_files: 10000,
      max_size_per_file: '5GB',
      api_calls_per_hour: 1000
    }
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Cloud storage and file sharing platform',
    category: INTEGRATION_CATEGORY_STORAGE,
    platform: 'web',
    status: 'complete',
    features: [
      'file_discovery',
      'real_time_sync',
      'metadata_extraction',
      'batch_processing',
      'preview_generation'
    ],
    oauth: {
      provider: 'dropbox',
      scopes: ['files.metadata.read', 'files.content.read', 'files.content.write'],
      flow: 'oauth2'
    },
    webhooks: [
      'file.added',
      'file.updated',
      'file.deleted',
      'folder.added'
    ],
    limits: {
      max_files: 10000,
      max_size_per_file: '2GB',
      api_calls_per_hour: 1600
    }
  },
  {
    id: 'gdrive',
    name: 'Google Drive',
    description: 'Cloud storage and document management platform',
    category: INTEGRATION_CATEGORY_STORAGE,
    platform: 'web',
    status: 'complete',
    features: [
      'file_discovery',
      'real_time_sync',
      'metadata_extraction',
      'batch_processing',
      'preview_generation'
    ],
    oauth: {
      provider: 'google',
      scopes: ['https://www.googleapis.com/auth/drive'],
      flow: 'oauth2'
    },
    webhooks: [
      'files.create',
      'files.update',
      'files.delete'
    ],
    limits: {
      max_files: 10000,
      max_size_per_file: '100GB',
      api_calls_per_hour: 10000
    }
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    description: 'Microsoft cloud storage and document management platform',
    category: INTEGRATION_CATEGORY_STORAGE,
    platform: 'web',
    status: 'complete',
    features: [
      'file_discovery',
      'real_time_sync',
      'metadata_extraction',
      'batch_processing',
      'preview_generation',
      'atom_ingestion',
      'microsoft_graph_integration',
      'resumable_upload',
      'version_control'
    ],
    oauth: {
      provider: 'microsoft',
      scopes: [
        'Files.ReadWrite',
        'Sites.ReadWrite.All',
        'User.Read',
        'offline_access'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'file.created',
      'file.updated',
      'file.deleted',
      'folder.created',
      'folder.updated',
      'folder.deleted'
    ],
    limits: {
      max_files: 100000,
      max_size_per_file: '250GB',
      api_calls_per_minute: 10000,
      upload_chunk_size: '320KB',
      max_concurrent_uploads: 3
    },
    skills: [
      'onedrive_search_files',
      'onedrive_upload_file',
      'onedrive_create_folder',
      'onedrive_sync_with_atom_memory'
    ],
    components: [
      'OneDriveIntegration',
      'OneDriveManager',
      'OneDriveAPIClient',
      'OneDriveSkillsBundle'
    ],
    dependencies: {
      'microsoft_graph_auth': 'Required for OneDrive API access',
      'atom_ingestion_pipeline': 'Required for ATOM memory synchronization',
      'fernet_encryption': 'Required for secure token storage'
    },
    supported_file_types: [
      'text/plain',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'image/jpeg',
      'image/png',
      'image/gif',
      'image/webp',
      'video/mp4',
      'video/quicktime',
      'audio/mpeg',
      'audio/wav'
    ],
    advanced_features: {
      'resumable_upload': true,
      'version_history': true,
      'real_time_collaboration': true,
      'offline_access': true,
      'sharing_permissions': true,
      'file_recovery': true,
      'advanced_search': true
    }
  },
  // Communication Integrations
  {
    id: 'slack',
    name: 'Slack',
    description: 'Team communication and collaboration platform',
    category: INTEGRATION_CATEGORY_COMMUNICATION,
    platform: 'web',
    status: 'complete',
    features: [
      'message_discovery',
      'real_time_events',
      'thread_processing',
      'attachment_processing',
      'user_context'
    ],
    oauth: {
      provider: 'slack',
      scopes: ['channels:read', 'channels:history', 'users:read', 'files:read'],
      flow: 'oauth2'
    },
    webhooks: [
      'message.channels',
      'message.private',
      'file.shared',
      'user.typing'
    ],
    limits: {
      max_messages: 50000,
      max_channels: 1000,
      api_calls_per_minute: 20
    }
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Email communication and organization platform',
    category: INTEGRATION_CATEGORY_COMMUNICATION,
    platform: 'web',
    status: 'complete',
    features: [
      'email_discovery',
      'contact_extraction',
      'header_extraction',
      'attachment_processing',
      'batch_processing'
    ],
    oauth: {
      provider: 'google',
      scopes: ['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.send'],
      flow: 'oauth2'
    },
    webhooks: [
      'message.added',
      'message.updated',
      'label.created'
    ],
    limits: {
      max_emails: 50000,
      max_attachments: 10000,
      api_calls_per_day: 1000000
    }
  },
  // Productivity & Enterprise Integration
  {
    id: 'microsoft365',
    name: 'Microsoft 365',
    description: 'Complete Microsoft 365 unified platform with Teams, Outlook, OneDrive, SharePoint, Power Platform, and enterprise productivity tools',
    category: INTEGRATION_CATEGORY_PRODUCTIVITY,
    platform: 'enterprise',
    status: 'complete',
    features: [
      'unified_authentication',
      'cross_service_workflows',
      'enterprise_management',
      'team_management',
      'channel_operations',
      'messaging',
      'meetings',
      'presence_status',
      'email_operations',
      'calendar_management',
      'contact_management',
      'task_management',
      'file_operations',
      'document_sharing',
      'version_control',
      'sync_management',
      'site_management',
      'content_collaboration',
      'document_library',
      'enterprise_search',
      'workflow_automation',
      'business_intelligence',
      'custom_applications',
      'data_integration',
      'real_time_collaboration',
      'advanced_analytics',
      'security_compliance',
      'audit_logging',
      'api_management',
      'rate_limiting',
      'multi_tenant_support',
      'conditional_access',
      'policy_management',
      'enterprise_governance',
      'usage_analytics',
      'service_health_monitoring',
      'backup_recovery',
      'mobile_synchronization',
      'desktop_integration',
      'web_application',
      'power_automate',
      'power_bi',
      'power_apps',
      'planner',
      'bookings',
      'viva',
      'loop',
      'whiteboard'
    ],
    oauth: {
      provider: 'microsoft',
      scopes: [
        'User.Read',
        'User.Read.All',
        'Mail.Read',
        'Mail.Send',
        'Calendars.Read',
        'Calendars.ReadWrite',
        'Files.Read',
        'Files.ReadWrite',
        'Team.ReadBasic.All',
        'Team.Create',
        'Channel.ReadBasic.All',
        'Channel.Create',
        'Chat.Read',
        'Chat.ReadWrite',
        'Sites.Read.All',
        'Sites.ReadWrite.All',
        'Flow.Read.All',
        'Flow.ReadWrite.All',
        'PowerBI.Dashboards.All',
        'Directory.Read.All',
        'Group.Read.All',
        'AppRoleAssignment.ReadWrite.All'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'message.created',
      'message.updated',
      'message.deleted',
      'channel.created',
      'channel.updated',
      'channel.deleted',
      'team.created',
      'team.updated',
      'team.deleted',
      'meeting.created',
      'meeting.updated',
      'meeting.started',
      'meeting.ended',
      'user.joined',
      'user.left',
      'presence.changed',
      'file.shared',
      'file.updated',
      'member.added',
      'member.removed',
      'calendar.event.created',
      'calendar.event.updated',
      'calendar.event.deleted',
      'document.created',
      'document.updated',
      'document.deleted',
      'site.created',
      'site.updated',
      'workflow.activated',
      'workflow.completed',
      'workflow.failed',
      'flow.triggered',
      'powerbi.report.updated',
      'app.installed',
      'app.uninstalled'
    ],
    limits: {
      max_integrations: 1000,
      max_tenant_connections: 50,
      max_teams: 1000,
      max_channels_per_team: 200,
      max_members_per_team: 25000,
      max_messages_per_channel: 500000,
      max_files_per_user: 500000,
      max_storage_per_user: '1TB',
      max_calendar_events: 10000,
      max_flows_per_user: 500,
      max_sites: 100,
      max_api_calls_per_minute: 6000,
      max_api_calls_per_hour: 30000,
      max_api_calls_per_day: 600000,
      max_concurrent_requests: 100,
      file_upload_size_limit: '250GB',
      email_recipients_limit: 500,
      meeting_participants_limit: 1000,
      webhook_events_per_minute: 1000,
      max_powerbi_dashboards: 1000,
      max_powerapps_per_user: 200,
      max_backup_retention_days: 365,
      max_audit_log_retention_days: 90,
      max_concurrent_workflows: 1000,
      max_report_generation_per_hour: 100
    }
  },
  // Work OS & Project Management
  {
    id: 'monday',
    name: 'Monday.com',
    description: 'Work OS platform that connects people, processes, and tools into one place for complete business management',
    category: INTEGRATION_CATEGORY_PRODUCTIVITY,
    platform: 'web',
    status: 'complete',
    features: [
      'board_management',
      'item_tracking',
      'column_management',
      'group_organization',
      'task_management',
      'timeline_view',
      'kanban_view',
      'calendar_view',
      'form_builder',
      'dashboard_analytics',
      'automation_workflows',
      'team_collaboration',
      'file_attachments',
      'notification_system',
      'search_filtering',
      'data_import_export',
      'api_integration',
      'custom_fields',
      'dependency_tracking',
      'milestone_management',
      'time_tracking',
      'resource_management',
      'reporting_insights',
      'permission_controls',
      'template_library',
      'integration_builder',
      'webhook_support',
      'audit_logging',
      'backup_recovery',
      'multi_workspace',
      'cross_board_automations',
      'form_submissions',
      'document_management',
      'mobile_synchronization',
      'offline_mode',
      'real_time_updates',
      'collaboration_tools',
      'enterprise_governance',
      'compliance_features',
      'advanced_analytics',
      'business_intelligence',
      'custom_automations',
      'third_party_connectors'
    ],
    oauth: {
      provider: 'monday',
      scopes: [
        'boards:read',
        'boards:write',
        'items:read',
        'items:write',
        'updates:read',
        'updates:write',
        'notifications:read',
        'notifications:write',
        'account:read',
        'users:read',
        'tags:read',
        'tags:write',
        'forms:read',
        'forms:write',
        'documents:read',
        'documents:write',
        'workspaces:read',
        'admin:read',
        'me:read',
        'webhooks:read',
        'webhooks:write'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'board.created',
      'board.updated',
      'board.deleted',
      'item.created',
      'item.updated',
      'item.deleted',
      'item.moved',
      'item.column_value_changed',
      'group.created',
      'group.updated',
      'group.deleted',
      'update.created',
      'update.updated',
      'update.deleted',
      'notification.created',
      'form.submitted',
      'automation.triggered',
      'automation.completed',
      'automation.failed',
      'file.uploaded',
      'file.deleted',
      'comment.created',
      'comment.updated',
      'comment.deleted',
      'user.added',
      'user.removed',
      'workspace.updated',
      'status.changed',
      'deadline.reached',
      'dependency.completed',
      'milestone.achieved'
    ],
    limits: {
      max_integrations: 100,
      max_workspaces: 25,
      max_boards_per_workspace: 200,
      max_items_per_board: 10000,
      max_columns_per_board: 200,
      max_groups_per_board: 100,
      max_subitems_per_item: 50,
      max_updates_per_item: 500,
      max_attachments_per_item: 100,
      max_file_size_mb: 100,
      max_api_requests_per_minute: 1000,
      max_automations_per_board: 50,
      max_webhooks_per_account: 50,
      max_forms_per_board: 25,
      max_guests_per_board: 100,
      max_admins_per_workspace: 10,
      max_readers_per_board: 1000,
      max_tags_per_workspace: 100,
      max_template_library: 1000,
      max_dashboard_widgets: 50,
      max_report_generation_per_hour: 100,
      max_export_items_per_request: 500,
      max_import_items_per_request: 1000,
      max_concurrent_webhooks: 25,
      max_history_retention_days: 365,
      max_backup_retention_days: 90,
      max_custom_fields_per_board: 100,
      max_dependencies_per_item: 20,
      max_milestones_per_board: 50,
      max_form_submissions_per_month: 10000,
      max_mobile_users_per_workspace: 100,
      max_team_members_per_workspace: 1000,
      max_cross_board_automations: 100
    }
  },
  // Communication Integrations
  {
    id: 'teams',
    name: 'Microsoft Teams',
    description: 'Team communication and collaboration platform with enterprise messaging and meeting capabilities',
    category: INTEGRATION_CATEGORY_COMMUNICATION,
    platform: 'web',
    status: 'complete',
    features: [
      'message_discovery',
      'channel_management',
      'team_management',
      'meeting_management',
      'file_sharing',
      'user_context',
      'real_time_events',
      'voice_video_calling',
      'screen_sharing',
      'message_search',
      'thread_conversations',
      'presence_indicators',
      'notification_management',
      'governance_compliance',
      'calling_policies',
      'app_integration',
      'bot_development',
      'api_access',
      'security_features',
      'multi_device_sync',
      'file_collaboration',
      'calendar_integration',
      'task_management',
      'third_party_apps',
      'meeting_recording',
      'transcription_services',
      'live_events',
      'breakout_rooms',
      'background_effects',
      'whiteboard_collaboration',
      'polls_quizzes',
      'presentations_sharing',
      'cloud_storage',
      'enterprise_policies',
      'access_controls',
      'audit_logging'
    ],
    oauth: {
      provider: 'microsoft',
      scopes: [
        'Chat.Read',
        'Chat.ReadWrite',
        'Channel.ReadBasic.All',
        'ChannelMessage.Read.All',
        'Team.ReadBasic.All',
        'User.Read.All',
        'Presence.Read',
        'Calls.JoinGroupCall.All',
        'Meetings.ReadWrite',
        'Files.Read',
        'Files.ReadWrite',
        'Sites.Read.All',
        'Sites.ReadWrite.All',
        'Contacts.Read',
        'Presence.Read.All',
        'ChannelMessage.Send',
        'OnlineMeetings.Read.All'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'message.created',
      'message.updated',
      'message.deleted',
      'channel.created',
      'channel.updated',
      'channel.deleted',
      'team.created',
      'team.updated',
      'team.deleted',
      'meeting.created',
      'meeting.updated',
      'meeting.started',
      'meeting.ended',
      'user.joined',
      'user.left',
      'presence.changed',
      'file.shared',
      'file.updated',
      'member.added',
      'member.removed',
      'app.installed',
      'app.uninstalled',
      'chat_thread.created',
      'chat_thread.updated',
      'call.started',
      'call.ended'
    ],
    limits: {
      max_messages: 1000000,
      max_channels_per_team: 200,
      max_teams: 1000,
      max_users_per_team: 25000,
      max_meeting_participants: 1000,
      api_calls_per_minute: 5000,
      api_calls_per_hour: 60000,
      webhook_events_per_minute: 1000,
      attachment_size_mb: 500,
      meeting_recording_hours: 24,
      concurrent_meetings: 1000,
      storage_per_user_gb: 25
    }
  },
  // Productivity Integrations
  {
    id: 'notion',
    name: 'Notion',
    description: 'Document management and knowledge base platform',
    category: INTEGRATION_CATEGORY_PRODUCTIVITY,
    platform: 'web',
    status: 'complete',
    features: [
      'page_discovery',
      'content_extraction',
      'block_processing',
      'database_query',
      'real_time_sync'
    ],
    oauth: {
      provider: 'notion',
      scopes: ['read_content', 'read_workspace'],
      flow: 'oauth2'
    },
    webhooks: [
      'page.created',
      'page.updated',
      'database.created',
      'database.rows.created'
    ],
    limits: {
      max_pages: 10000,
      max_blocks: 100000,
      api_calls_per_minute: 20
    }
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Project management and issue tracking platform',
    category: INTEGRATION_CATEGORY_PRODUCTIVITY,
    platform: 'web',
    status: 'complete',
    features: [
      'issue_discovery',
      'project_sync',
      'comment_processing',
      'workflow_extraction',
      'real_time_events'
    ],
    oauth: {
      provider: 'atlassian',
      scopes: ['read:jira-work', 'read:jira-user'],
      flow: 'oauth2'
    },
    webhooks: [
      'issue.created',
      'issue.updated',
      'project.updated',
      'sprint.created'
    ],
    limits: {
      max_issues: 50000,
      max_projects: 1000,
      api_calls_per_hour: 1000
    }
  },
  // Development Integrations
  {
    id: 'github',
    name: 'GitHub',
    description: 'Code repository and development platform',
    category: INTEGRATION_CATEGORY_DEVELOPMENT,
    platform: 'web',
    status: 'complete',
    features: [
      'repository_discovery',
      'code_analysis',
      'issue_tracking',
      'pull_request_processing',
      'commit_history',
      'release_management'
    ],
    oauth: {
      provider: 'github',
      scopes: ['repo', 'read:user', 'read:org'],
      flow: 'oauth2'
    },
    webhooks: [
      'push',
      'pull_request',
      'issues',
      'release'
    ],
    limits: {
      max_repos: 1000,
      max_commits: 100000,
      api_calls_per_hour: 5000
    }
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: 'Vercel project management and deployment platform',
    category: INTEGRATION_CATEGORY_DEVELOPMENT,
    platform: 'web',
    status: 'complete',
    features: [
      'project_discovery',
      'deployment_tracking',
      'build_monitoring',
      'analytics_integration',
      'environment_variable_management',
      'real_time_build_updates',
      'deployment_automation',
      'performance_optimization',
      'webhook_integration'
    ],
    oauth: {
      provider: 'vercel',
      scopes: ['read', 'write', 'projects', 'deployments', 'builds'],
      flow: 'oauth2'
    },
    webhooks: [
      'deployment.created',
      'deployment.ready',
      'deployment.error',
      'build.created',
      'build.ready',
      'build.error'
    ],
    limits: {
      max_projects: 1000,
      max_deployments: 10000,
      max_builds: 50000,
      api_calls_per_hour: 1000
    }
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Communication platform for communities and teams',
    category: INTEGRATION_CATEGORY_COMMUNICATION,
    platform: 'web',
    status: 'complete',
    features: [
      'server_management',
      'channel_management',
      'message_sending',
      'user_authentication',
      'bot_integration',
      'voice_channels',
      'role_management',
      'webhook_support',
      'api_access'
    ],
    oauth: {
      provider: 'discord',
      scopes: ['bot', 'identify', 'guilds', 'messages.read'],
      flow: 'oauth2'
    },
    webhooks: [
      'message.create',
      'message.update',
      'message.delete',
      'guild.member.add',
      'guild.member.remove',
      'channel.create',
      'channel.update',
      'channel.delete'
    ],
    limits: {
      max_guilds: 100,
      max_channels_per_guild: 500,
      max_members_per_guild: 250000,
      api_calls_per_second: 50,
      api_calls_per_minute: 1200
    }
  },
  // Development Tools Integrations
  {
    id: 'linear',
    name: 'Linear',
    description: 'Modern issue tracking and project management for software development teams',
    category: INTEGRATION_CATEGORY_DEVELOPMENT,
    platform: 'web',
    status: 'complete',
    features: [
      'issue_tracking',
      'project_management',
      'team_collaboration',
      'issue_assignment',
      'status_tracking',
      'priority_management',
      'milestone_tracking',
      'time_tracking',
      'issue_comments',
      'attachments',
      'labels',
      'milestones',
      'release_tracking',
      'automations',
      'webhooks',
      'api_access',
      'real_time_updates',
      'issue_templates',
      'custom_fields',
      'issue_history',
      'search_filtering',
      'bulk_operations',
      'reporting',
      'team_dashboards',
      'productivity_metrics',
      'integration_apis'
    ],
    oauth: {
      provider: 'linear',
      scopes: [
        'read',
        'write',
        'issues:read',
        'issues:write',
        'projects:read',
        'projects:write',
        'teams:read',
        'teams:write',
        'users:read',
        'labels:read',
        'labels:write',
        'webhooks:read',
        'webhooks:write'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'Issue.created',
      'Issue.updated',
      'Issue.removed',
      'Issue.completed',
      'Issue.archived',
      'Issue.reopened',
      'Issue.status_changed',
      'Issue.assignee_changed',
      'Issue.priority_changed',
      'Issue.title_changed',
      'Issue.description_changed',
      'Issue.comment_created',
      'Issue.comment_updated',
      'Issue.attachment_created',
      'Project.created',
      'Project.updated',
      'Project.removed',
      'Team.created',
      'Team.updated',
      'Team.member_added',
      'Team.member_removed',
      'User.created',
      'User.updated',
      'Label.created',
      'Label.updated',
      'Label.removed',
      'Milestone.created',
      'Milestone.updated',
      'Milestone.completed'
    ],
    limits: {
      max_issues_per_project: 100000,
      max_projects_per_team: 1000,
      max_teams_per_workspace: 100,
      max_users_per_workspace: 5000,
      max_webhooks_per_workspace: 100,
      api_calls_per_minute: 1000,
      api_calls_per_hour: 60000,
      attachment_size_mb: 10,
      max_attachments_per_issue: 100
    }
  },
  // Data Management & Productivity Integrations
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Cloud-based database and spreadsheet platform with workflow automation capabilities',
    category: INTEGRATION_CATEGORY_PRODUCTIVITY,
    platform: 'web',
    status: 'complete',
    features: [
      'database_management',
      'table_operations',
      'record_processing',
      'view_customization',
      'formula_computation',
      'api_integration',
      'data_validation',
      'relationship_linking',
      'collaboration_tools',
      'automation_workflows',
      'import_export',
      'search_filtering',
      'sort_grouping',
      'calculations_aggregations',
      'data_visualization',
      'form_creation',
      'field_types',
      'record_templates',
      'revision_history',
      'collaborative_editing',
      'access_controls',
      'api_rate_limiting',
      'sync_integration',
      'backup_restore',
      'scripting_automation',
      'webhook_triggers',
      'custom_apis',
      'enterprise_security',
      'audit_logging'
    ],
    oauth: {
      provider: 'airtable',
      scopes: [
        'data.records:read',
        'data.records:write',
        'schema.bases:read',
        'schema.tables:read',
        'users:read',
        'webhooks:manage'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'table.records.created',
      'table.records.updated',
      'table.records.deleted',
      'base.created',
      'base.updated',
      'table.created',
      'base.shared',
      'collaborator.added',
      'collaborator.removed',
      'webhook.test',
      'automation.triggered',
      'script.executed'
    ],
    limits: {
      max_bases: 100,
      max_tables_per_base: 1000,
      max_records_per_table: 50000,
      max_fields_per_table: 1000,
      max_form_responses_per_form: 10000,
      max_automations_per_base: 50,
      max_scripts_per_base: 25,
      api_calls_per_second: 5,
      api_calls_per_minute: 100,
      webhook_events_per_minute: 1000,
      attachment_size_mb: 25,
      max_views_per_table: 100,
      max_form_fields: 1000,
      max_collaborators_per_base: 1000
    }
  },
  // Project Management & Productivity Integrations
  {
    id: 'asana',
    name: 'Asana',
    description: 'Work management and project coordination platform for teams',
    category: INTEGRATION_CATEGORY_PRODUCTIVITY,
    platform: 'web',
    status: 'complete',
    features: [
      'task_management',
      'project_tracking',
      'team_coordination',
      'workflow_automation',
      'deadline_monitoring',
      'dependency_tracking',
      'collaboration_tools',
      'file_attachments',
      'comment_threads',
      'status_updates',
      'milestone_tracking',
      'resource_allocation',
      'progress_tracking',
      'team_assignments',
      'task_dependencies',
      'project_templates',
      'time_tracking',
      'workload_management',
      'integrations',
      'api_access',
      'real_time_updates',
      'custom_fields',
      'advanced_search',
      'reporting',
      'dashboard_analytics'
    ],
    oauth: {
      provider: 'asana',
      scopes: [
        'default',
        'tasks:read',
        'tasks:write',
        'projects:read',
        'projects:write',
        'teams:read',
        'stories:read',
        'stories:write',
        'attachments:read',
        'attachments:write',
        'events:read',
        'goals:read',
        'goals:write',
        'portfolio:read',
        'portfolio:write'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'Task.created',
      'Task.updated',
      'Task.completed',
      'Task.removed',
      'Task.assigned',
      'Task.unassigned',
      'Task.dependency_added',
      'Task.dependency_removed',
      'Task.status_changed',
      'Task.due_date_changed',
      'Task.priority_changed',
      'Task.project_changed',
      'Task.tags_changed',
      'Task.custom_fields_changed',
      'Story.created',
      'Story.updated',
      'Story.removed',
      'Story.attachment_added',
      'Story.attachment_removed',
      'Project.created',
      'Project.updated',
      'Project.removed',
      'Project.status_changed',
      'Project.archived',
      'Project.team_changed',
      'Team.added',
      'Team.removed',
      'Team.updated',
      'Team.name_changed',
      'Goal.created',
      'Goal.updated',
      'Goal.completed',
      'Goal.progress_changed',
      'Portfolio.created',
      'Portfolio.updated',
      'Portfolio.item_added',
      'Portfolio.item_removed'
    ],
    limits: {
      max_tasks_per_project: 100000,
      max_projects: 10000,
      max_teams: 1000,
      max_users_per_team: 10000,
      max_attachments_per_task: 100,
      max_comments_per_task: 1000,
      api_calls_per_minute: 1500,
      api_calls_per_hour: 60000,
      webhook_events_per_minute: 1000,
      attachment_size_mb: 100,
      max_custom_fields: 100
    }
  },
  // Financial & Accounting Integrations
  {
    id: 'xero',
    name: 'Xero',
    description: 'Complete small business accounting and financial management platform',
    category: INTEGRATION_CATEGORY_FINANCIAL,
    platform: 'web',
    status: 'complete',
    features: [
      'invoice_management',
      'contact_management',
      'bank_reconciliation',
      'financial_reporting',
      'expense_tracking',
      'tax_management',
      'payment_processing',
      'budget_tracking',
      'cash_flow_management',
      'multi_currency_support',
      'bank_feeds',
      'reconciliation_automation',
      'inventory_tracking',
      'payroll_management',
      'project_accounting',
      'time_tracking',
      'fixed_assets',
      'bill_management',
      'quoting',
      'mobile_access',
      'api_integration',
      'webhook_support',
      'multi_organization',
      'audit_trails',
      'compliance_reporting'
    ],
    oauth: {
      provider: 'xero',
      scopes: [
        'openid',
        'profile',
        'email',
        'accounting.settings',
        'accounting.transactions',
        'accounting.reports.read',
        'accounting.journals.read',
        'accounting.contacts',
        'accounting.attachments',
        'accounting.budgets.read',
        'offline_access'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'Invoice.Created',
      'Invoice.Updated',
      'Invoice.Paid',
      'Invoice.Voided',
      'Invoice.Deleted',
      'Contact.Created',
      'Contact.Updated',
      'Contact.Deleted',
      'BankTransaction.Created',
      'BankTransaction.Updated',
      'BankTransaction.Deleted',
      'Payment.Created',
      'Payment.Updated',
      'Payment.Deleted',
      'Expense.Claim.Created',
      'Expense.Claim.Updated',
      'Expense.Claim.Approved',
      'Expense.Claim.Paid',
      'Journal.Created',
      'Journal.Updated',
      'Journal.Posted',
      'ManualJournal.Created',
      'ManualJournal.Updated',
      'ManualJournal.Posted',
      'Item.Created',
      'Item.Updated',
      'Item.Deleted',
      'PurchaseOrder.Created',
      'PurchaseOrder.Updated',
      'PurchaseOrder.Approved',
      'PurchaseOrder.EmailSent'
    ],
    limits: {
      max_invoices_per_month: 10000,
      max_contacts: 10000,
      max_bank_accounts: 100,
      max_transactions_per_day: 5000,
      max_reports_per_month: 1000,
      max_users: 100,
      api_calls_per_day: 5000,
      api_calls_per_minute: 60,
      attachment_size_mb: 25,
      max_attachments_per_entity: 100
    }
  },
  // Customer Service Integrations
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Complete customer support and ticketing management platform',
    category: INTEGRATION_CATEGORY_CUSTOMER_SERVICE,
    platform: 'web',
    status: 'complete',
    features: [
      'ticket_management',
      'customer_support',
      'user_management',
      'group_management',
      'organization_management',
      'knowledge_base',
      'automation',
      'ai_insights',
      'sentiment_analysis',
      'ticket_routing',
      'satisfaction_tracking',
      'multi_channel_support',
      'real_time_chat',
      'phone_integration',
      'email_integration',
      'social_integration',
      'self_service_portal',
      'community_forum',
      'help_center',
      'sla_management',
      'reporting_analytics',
      'custom_fields',
      'macros',
      'triggers',
      'automations',
      'multi_brand_support',
      'sdk_integration',
      'webhook_support'
    ],
    oauth: {
      provider: 'zendesk',
      scopes: [
        'tickets:read',
        'tickets:write',
        'users:read',
        'users:write',
        'organizations:read',
        'organizations:write',
        'groups:read',
        'groups:write',
        'macros:read',
        'automations:read',
        'triggers:read',
        'satisfaction:read',
        'forums:read',
        'topics:read',
        'posts:read',
        'articles:read',
        'webhooks:read',
        'webhooks:write'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'ticket.created',
      'ticket.updated',
      'ticket.deleted',
      'ticket.merged',
      'ticket.changed',
      'comment.created',
      'comment.updated',
      'comment.deleted',
      'user.created',
      'user.updated',
      'user.deleted',
      'organization.created',
      'organization.updated',
      'organization.deleted',
      'group.created',
      'group.updated',
      'group.deleted',
      'satisfaction.created',
      'satisfaction.updated',
      'voice-call.started',
      'voice-call.completed',
      'voice-call.missed',
      'chat.conversation.started',
      'chat.conversation.updated',
      'chat.conversation.ended',
      'macro.applied',
      'automation.applied',
      'trigger.applied'
    ],
    limits: {
      max_tickets: 5000000,
      max_users: 1000000,
      max_groups: 10000,
      max_organizations: 1000000,
      max_articles: 100000,
      max_webhooks: 100,
      api_calls_per_minute: 700,
      api_calls_per_hour: 42000,
      upload_size_mb: 50
    }
  },
  // Customer Service Integrations
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    description: 'Complete customer support and help desk platform with ticketing, knowledge base, and multi-channel support',
    category: INTEGRATION_CATEGORY_CUSTOMER_SERVICE,
    platform: 'web',
    status: 'complete',
    features: [
      'ticket_management',
      'customer_support',
      'contact_management',
      'company_management',
      'agent_management',
      'group_management',
      'knowledge_base',
      'multi_channel_support',
      'ticket_automation',
      'sla_management',
      'priority_management',
      'status_tracking',
      'assignment_rules',
      'escalation_workflows',
      'customer_satisfaction',
      'feedback_collection',
      'reporting_analytics',
      'custom_fields',
      'canned_responses',
      'time_tracking',
      'internal_notes',
      'collaboration_tools',
      'email_integration',
      'phone_integration',
      'chat_integration',
      'social_media_integration',
      'api_access',
      'webhook_support',
      'mobile_support',
      'multi_language',
      'custom_branding',
      'automation_rules',
      'macros',
      'triggers',
      'ticket_templates',
      'dashboard_analytics',
      'performance_metrics',
      'customer_segmentation',
      'bulk_operations',
      'import_export',
      'audit_logging',
      'security_controls',
      'role_based_access',
      'data_privacy',
      'gdpr_compliance',
      'backup_restore'
    ],
    oauth: {
      provider: 'freshdesk',
      scopes: [
        'tickets:read',
        'tickets:write',
        'contacts:read',
        'contacts:write',
        'companies:read',
        'companies:write',
        'agents:read',
        'groups:read',
        'conversations:read',
        'conversations:write',
        'solutions:read',
        'solutions:write',
        'forums:read',
        'forums:write',
        'analytics:read',
        'reports:read',
        'surveys:read',
        'surveys:write',
        'webhooks:read',
        'webhooks:write',
        'automations:read',
        'automations:write',
        'custom_fields:read',
        'custom_fields:write',
        'scenarios:read',
        'scenarios:write',
        'admin:read',
        'admin:write'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'ticket.created',
      'ticket.updated',
      'ticket.deleted',
      'ticket.status_changed',
      'ticket.priority_changed',
      'ticket.assigned',
      'ticket.unassigned',
      'ticket.reopened',
      'ticket.resolved',
      'ticket.closed',
      'contact.created',
      'contact.updated',
      'contact.deleted',
      'contact.merged',
      'company.created',
      'company.updated',
      'company.deleted',
      'agent.created',
      'agent.updated',
      'agent.deleted',
      'agent.status_changed',
      'group.created',
      'group.updated',
      'group.deleted',
      'conversation.created',
      'conversation.updated',
      'conversation.replied',
      'conversation.note_added',
      'solution.article.created',
      'solution.article.updated',
      'solution.article.published',
      'solution.article.deleted',
      'forum.topic.created',
      'forum.topic.updated',
      'forum.topic.deleted',
      'forum.post.created',
      'forum.post.updated',
      'survey.response.created',
      'survey.updated',
      'automation.rule.triggered',
      'automation.rule.completed',
      'scenario.executed',
      'custom_field.created',
      'custom_field.updated',
      'custom_field.deleted',
      'sla.breached',
      'escalation.triggered',
      'satisfaction.rating.updated',
      'feedback.received',
      'user.login',
      'user.logout',
      'data.exported',
      'data.imported'
    ],
    limits: {
      max_tickets: 1000000,
      max_contacts: 500000,
      max_companies: 50000,
      max_agents: 1000,
      max_groups: 100,
      max_articles: 10000,
      max_forums: 100,
      max_automations: 500,
      max_webhooks: 50,
      api_calls_per_minute: 1000,
      api_calls_per_hour: 60000,
      attachment_size_mb: 50,
      max_attachments_per_ticket: 100,
      max_conversations_per_ticket: 500,
      max_custom_fields: 200,
      max_scenarios: 100,
      max_sla_policies: 50,
      max_ticket_fields: 100,
      max_canned_responses: 1000,
      max_dashboard_widgets: 50,
      max_report_generation_per_hour: 100,
      max_export_tickets_per_request: 1000,
      max_import_tickets_per_request: 500,
      concurrent_webhooks: 25,
      history_retention_days: 365,
      backup_retention_days: 90,
      max_chat_agents: 50,
      max_phone_agents: 100,
      max_social_accounts: 20,
      max_languages_supported: 30
    }
  },
  // Marketing & CRM Integrations
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Complete CRM, marketing, and sales automation platform',
    category: INTEGRATION_CATEGORY_MARKETING,
    platform: 'web',
    status: 'complete',
    features: [
      'contact_management',
      'company_management',
      'deal_pipeline',
      'marketing_automation',
      'email_campaigns',
      'lead_scoring',
      'analytics_reporting',
      'sales_forecasting',
      'ai_insights',
      'workflow_automation',
      'ticket_management',
      'live_chat',
      'social_media_integration',
      'landing_pages',
      'forms',
      'call_tracking',
      'meeting_scheduling'
    ],
    oauth: {
      provider: 'hubspot',
      scopes: [
        'contacts',
        'companies',
        'deals',
        'marketing',
        'sales',
        'tickets',
        'automation',
        'integration-bridge',
        'e-commerce',
        'settings',
        'analytics',
        'business-intelligence'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'contact.creation',
      'contact.deletion',
      'contact.propertyChange',
      'company.creation',
      'company.deletion',
      'company.propertyChange',
      'deal.creation',
      'deal.deletion',
      'deal.propertyChange',
      'ticket.creation',
      'ticket.deletion',
      'ticket.propertyChange',
      'marketing.email',
      'subscription.change'
    ],
    limits: {
      max_contacts: 1000000,
      max_companies: 100000,
      max_deals: 500000,
      max_tickets: 1000000,
      api_calls_per_10_seconds: 100,
      api_calls_per_day: 250000
    }
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Complete CRM platform with sales, service, marketing, and customer relationship management',
    category: INTEGRATION_CATEGORY_MARKETING,
    platform: 'web',
    status: 'complete',
    features: [
      'account_management',
      'contact_management',
      'lead_management',
      'opportunity_tracking',
      'case_management',
      'campaign_management',
      'quote_generation',
      'order_management',
      'invoice_management',
      'product_catalog',
      'price_book_management',
      'contract_management',
      'solution_tracking',
      'custom_objects',
      'workflow_automation',
      'approval_processes',
      'reporting_dashboard',
      'analytics_insights',
      'email_integration',
      'social_integrations',
      'mobile_app',
      'api_access',
      'data_import_export',
      'custom_fields',
      'validation_rules',
      'duplicate_detection',
      'territory_management',
      'forecasting_tools',
      'collaboration_tools',
      'chatter_social',
      'knowledge_base',
      'community_portal',
      'appexchange_marketplace',
      'lightning_platform',
      'heroku_integration',
      'tableau_analytics',
      'einstein_ai',
      'customer_360_view',
      'omni_channel_support',
      'journey_builder',
      'marketing_cloud',
      'commerce_cloud',
      'service_cloud',
      'sales_cloud',
      'financial_cloud',
      'health_cloud',
      'education_cloud',
      'slack_integration',
      'microsoft_teams',
      'outlook_integration',
      'calendar_sync',
      'document_generation',
      'electronic_signatures',
      'payment_processing',
      'tax_calculation',
      'multi_currency',
      'multi_language',
      'compliance_features',
      'audit_trail',
      'security_controls',
      'role_hierarchy',
      'permission_sets',
      'field_security',
      'sharing_rules',
      'encryption_rest',
      'backup_recovery',
      'disaster_recovery',
      'sla_monitoring',
      'performance_analytics',
      'usage_metrics',
      'integration_builder',
      'custom_app_development',
      'api_testing_tools',
      'bulk_data_operations',
      'real_time_sync',
      'push_notifications',
      'email_templates',
      'custom_reports',
      'dashboard_widgets',
      'mobile_sdk',
      'offline_capabilities',
      'progressive_web_app'
    ],
    oauth: {
      provider: 'salesforce',
      scopes: [
        'api',
        'refresh_token',
        'full',
        'chatter_api',
        'visualforce',
        'lightning',
        'rest_api',
        'soap_api',
        'metadata',
        'custom_permissions',
        'app_access',
        'email',
        'offline_access',
        'profile',
        'user_management',
        'cdp_api',
        'marketing_cloud_api',
        'commerce_cloud_api',
        'service_cloud_api',
        'sales_cloud_api',
        'financial_cloud_api',
        'health_cloud_api',
        'education_cloud_api',
        'einstein_api',
        'analytics_api',
        'reporting_api',
        'dashboard_api',
        'web',
        'mobile_sdk'
      ],
      flow: 'oauth2'
    },
    webhooks: [
      'account.created',
      'account.updated',
      'account.deleted',
      'contact.created',
      'contact.updated',
      'contact.deleted',
      'lead.created',
      'lead.updated',
      'lead.deleted',
      'lead.converted',
      'opportunity.created',
      'opportunity.updated',
      'opportunity.deleted',
      'opportunity.won',
      'opportunity.lost',
      'case.created',
      'case.updated',
      'case.deleted',
      'case.closed',
      'campaign.created',
      'campaign.updated',
      'campaign.deleted',
      'campaign.started',
      'campaign.completed',
      'task.created',
      'task.updated',
      'task.completed',
      'event.created',
      'event.updated',
      'event.deleted',
      'quote.created',
      'quote.updated',
      'quote.accepted',
      'quote.rejected',
      'order.created',
      'order.updated',
      'order.completed',
      'order.cancelled',
      'invoice.created',
      'invoice.updated',
      'invoice.paid',
      'invoice.overdue',
      'product.created',
      'product.updated',
      'product.deleted',
      'pricebook.created',
      'pricebook.updated',
      'pricebook.deleted',
      'contract.created',
      'contract.updated',
      'contract.activated',
      'contract.expired',
      'solution.created',
      'solution.updated',
      'solution.deleted',
      'workflow.triggered',
      'workflow.completed',
      'workflow.failed',
      'approval.requested',
      'approval.approved',
      'approval.rejected',
      'file.created',
      'file.deleted',
      'file.shared',
      'chatter.posted',
      'chatter.commented',
      'chatter.liked',
      'email.sent',
      'email.opened',
      'email.clicked',
      'call.completed',
      'meeting.scheduled',
      'meeting.completed',
      'custom_object.created',
      'custom_object.updated',
      'custom_object.deleted',
      'data_imported',
      'data.exported',
      'sync.started',
      'sync.completed',
      'sync.failed',
      'user.login',
      'user.logout',
      'permission.changed',
      'role.changed',
      'api_limit.reached',
      'quota.exceeded',
      'backup.created',
      'backup.completed',
      'restore.started',
      'restore.completed',
      'mobile_app.installed',
      'mobile_app.removed',
      'app_installed',
      'app.uninstalled',
      'app_updated',
      'system.maintenance',
      'security.alert',
      'compliance.violation',
      'audit.log.created',
      'performance.threshold',
      'user.activity',
      'team.performance',
      'forecast.updated',
      'pipeline.changed',
      'territory.assigned',
      'territory.changed',
      'campaign.member.added',
      'campaign.member.removed',
      'subscription.created',
      'subscription.updated',
      'subscription.cancelled',
      'renewal.triggered',
      'renewal.completed',
      'escalation.created',
      'escalation.acknowledged',
      'escalation.resolved'
    ],
    limits: {
      max_api_requests_per_24h: 15000,
      max_concurrent_requests: 100,
      max_bulk_records_per_job: 50000,
      max_custom_objects: 200,
      max_custom_fields_per_object: 100,
      max_workflow_rules: 50,
      max_appexchanges_apps: 100,
      max_users_per_org: 10000,
      max_storage_per_user_gb: 5,
      max_email_templates: 1000,
      max_reports_per_dashboard: 20,
      max_dashboards_per_user: 50,
      max_concurrent_bulk_jobs: 5,
      max_api_call_timeout_sec: 120,
      max_file_upload_mb: 100,
      max_soap_calls_per_day: 1000,
      max_rest_calls_per_day: 15000,
      max_bulk_jobs_per_day: 20,
      max_sync_requests_per_minute: 60,
      max_mobile_devices_per_user: 10,
      max_automation_executions_per_hour: 250,
      max_approval_processes_per_user: 100,
      max_territories_per_org: 1000,
      max_campaigns_per_user: 100,
      max_leads_per_campaign: 50000,
      max_contacts_per_campaign: 50000,
      max_forecast_items_per_object: 200,
      max_pricebooks_per_org: 2000,
      max_products_per_pricebook: 1000,
      max_quotes_per_user: 1000,
      max_orders_per_day: 10000,
      max_invoices_per_month: 10000,
      max_cases_per_user: 5000,
      max_contracts_per_user: 1000,
      max_solutions_per_user: 1000,
      max_attachments_per_email: 25,
      max_email_attachments_mb: 25,
      max_chatter_posts_per_day: 100,
      max_dashboard_refresh_interval_sec: 300,
      max_report_export_rows: 200000,
      max_api_batch_size: 200,
      max_sosl_queries_per_day: 20,
      max_sosl_query_length: 4000,
      max_soql_query_length: 20000,
      max_soap_query_timeout_sec: 60,
      max_rest_query_timeout_sec: 120,
      max_bulk_api_timeout_sec: 600,
      max_realtime_event_subscriptions: 1000,
      max_push_notifications_per_hour: 100,
      max_data_import_size_mb: 100,
      max_data_export_size_mb: 200,
      max_custom_reports: 1000,
      max_dashboard_widgets: 50,
      max_app_extensions: 10,
      max_mobile_sessions_per_user: 5,
      max_offline_data_sync_mb: 50,
      max_compliance_rules: 100,
      max_audit_log_retention_days: 365,
      max_backup_retention_days: 90,
      max_disaster_recovery_retention_days: 30,
      max_performance_monitoring_metrics: 500,
      max_security_alert_rules: 100,
      max_multi_currency_codes: 20,
      max_multi_language_locales: 50,
      max_integration_connections: 100,
      max_webhook_subscriptions: 50,
      max_third_party_applications: 100,
      max_scheduled_jobs_per_hour: 50,
      max_email_campaign_recipients: 100000,
      max_sms_campaign_recipients: 50000,
      max_social_media_integrations: 20,
      max_omni_channel_conversations: 10000,
      max_customer_service_cases: 100000,
      max_sales_pipeline_stages: 50,
      max_lead_scoring_rules: 100,
      max_automated_workflows: 1000,
      max_approval_request_deadlines: 30,
      max_custom_validation_rules: 200,
      max_duplicate_detection_rules: 50,
      max_sharing_rules_per_object: 100,
      max_permission_sets: 1000,
      max_role_hierarchy_levels: 10,
      max_field_security_rules: 500,
      max_encryption_keys: 100,
      max_backup_frequency_hours: 24,
      max_restore_frequency_hours: 168
    }
  },
  zendesk: {
    name: 'Zendesk',
    auth_url: 'https://{subdomain}.zendesk.com/oauth/authorizations/new',
    token_url: 'https://{subdomain}.zendesk.com/oauth/tokens',
    scopes: [
      'tickets:read',
      'tickets:write',
      'users:read',
      'users:write',
      'organizations:read',
      'organizations:write',
      'groups:read',
      'groups:write',
      'macros:read',
      'automations:read',
      'triggers:read',
      'satisfaction:read',
      'forums:read',
      'topics:read',
      'posts:read',
      'articles:read',
      'webhooks:read',
      'webhooks:write'
    ]
  }
];

// Integration Category Mapping
export const INTEGRATIONS_BY_CATEGORY = ATOM_INTEGRATIONS.reduce((acc, integration) => {
  if (!acc[integration.category]) {
    acc[integration.category] = [];
  }
  acc[integration.category].push(integration);
  return acc;
}, {} as Record<string, typeof ATOM_INTEGRATIONS>);

// Platform Support
export const PLATFORMS = ['web', 'tauri', 'nextjs'] as const;

// Integration Status
export const INTEGRATION_STATUS = {
  complete: {
    label: 'Complete',
    color: 'green',
    description: 'Fully implemented and production ready'
  },
  in_progress: {
    label: 'In Progress',
    color: 'yellow',
    description: 'Currently under development'
  },
  planned: {
    label: 'Planned',
    color: 'gray',
    description: 'Scheduled for future development'
  }
} as const;

// OAuth Providers
export const OAUTH_PROVIDERS = {
  box: {
    name: 'Box',
    auth_url: 'https://account.box.com/api/oauth2/authorize',
    token_url: 'https://api.box.com/oauth2/token',
    scopes: ['read', 'write', 'manage']
  },
  dropbox: {
    name: 'Dropbox',
    auth_url: 'https://www.dropbox.com/oauth2/authorize',
    token_url: 'https://api.dropboxapi.com/oauth2/token',
    scopes: ['files.metadata.read', 'files.content.read', 'files.content.write']
  },
  google: {
    name: 'Google',
    auth_url: 'https://accounts.google.com/o/oauth2/v2/auth',
    token_url: 'https://oauth2.googleapis.com/token',
    scopes: ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/gmail.readonly']
  },
  slack: {
    name: 'Slack',
    auth_url: 'https://slack.com/oauth/v2/authorize',
    token_url: 'https://slack.com/api/oauth.v2.access',
    scopes: ['channels:read', 'channels:history', 'users:read', 'files:read']
  },
  notion: {
    name: 'Notion',
    auth_url: 'https://api.notion.com/v1/oauth/authorize',
    token_url: 'https://api.notion.com/v1/oauth/token',
    scopes: ['read_content', 'read_workspace']
  },
  atlassian: {
    name: 'Atlassian',
    auth_url: 'https://auth.atlassian.com/authorize',
    token_url: 'https://auth.atlassian.com/oauth/token',
    scopes: ['read:jira-work', 'read:jira-user']
  },
  github: {
    name: 'GitHub',
    auth_url: 'https://github.com/login/oauth/authorize',
    token_url: 'https://github.com/login/oauth/access_token',
    scopes: ['repo', 'read:user', 'read:org']
  },
  vercel: {
    name: 'Vercel',
    auth_url: 'https://vercel.com/oauth/authorize',
    token_url: 'https://api.vercel.com/v2/oauth/access_token',
    scopes: ['read', 'write', 'projects', 'deployments', 'builds']
  },
  hubspot: {
    name: 'HubSpot',
    auth_url: 'https://app.hubspot.com/oauth/authorize',
    token_url: 'https://api.hubapi.com/oauth/v1/token',
    scopes: [
      'contacts',
      'companies', 
      'deals',
      'marketing',
      'sales',
      'tickets',
      'automation',
      'integration-bridge',
      'e-commerce',
      'settings',
      'analytics',
      'business-intelligence'
    ]
  },
  linear: {
    name: 'Linear',
    auth_url: 'https://linear.app/oauth/authorize',
    token_url: 'https://api.linear.app/graphql',
    scopes: [
      'read',
      'write',
      'issues:read',
      'issues:write',
      'projects:read',
      'projects:write',
      'teams:read',
      'teams:write',
      'users:read',
      'labels:read',
      'labels:write',
      'webhooks:read',
      'webhooks:write'
    ]
  },
  xero: {
    name: 'Xero',
    auth_url: 'https://login.xero.com/identity/connect/authorize',
    token_url: 'https://identity.xero.com/connect/token',
    scopes: [
      'openid',
      'profile',
      'email',
      'accounting.settings',
      'accounting.transactions',
      'accounting.reports.read',
      'accounting.journals.read',
      'accounting.contacts',
      'accounting.attachments',
      'accounting.budgets.read',
      'offline_access'
    ]
  },
  asana: {
    name: 'Asana',
    auth_url: 'https://app.asana.com/-/oauth_authorize',
    token_url: 'https://app.asana.com/-/oauth_token',
    scopes: [
      'default',
      'tasks:read',
      'tasks:write',
      'projects:read',
      'projects:write',
      'teams:read',
      'stories:read',
      'stories:write',
      'attachments:read',
      'attachments:write',
      'events:read',
      'goals:read',
      'goals:write',
      'portfolio:read',
      'portfolio:write'
    ]
  },
  microsoft: {
    name: 'Microsoft',
    auth_url: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    token_url: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    scopes: [
      'Chat.Read',
      'Chat.ReadWrite',
      'Channel.ReadBasic.All',
      'ChannelMessage.Read.All',
      'Team.ReadBasic.All',
      'User.Read.All',
      'Presence.Read',
      'Calls.JoinGroupCall.All',
      'Meetings.ReadWrite',
      'Files.Read',
      'Files.ReadWrite',
      'Sites.Read.All',
      'Sites.ReadWrite.All',
      'Contacts.Read',
      'Presence.Read.All',
      'ChannelMessage.Send',
      'OnlineMeetings.Read.All'
    ]
  },
  airtable: {
    name: 'Airtable',
    auth_url: 'https://airtable.com/oauth2/v1/authorize',
    token_url: 'https://airtable.com/oauth2/v1/token',
    scopes: [
      'data.records:read',
      'data.records:write',
      'schema.bases:read',
      'schema.tables:read',
      'users:read',
      'webhooks:manage'
    ]
  },
  freshdesk: {
    name: 'Freshdesk',
    auth_url: 'https://{domain}.freshdesk.com/oauth/authorize',
    token_url: 'https://{domain}.freshdesk.com/oauth/token',
    scopes: [
      'tickets:read',
      'tickets:write',
      'contacts:read',
      'contacts:write',
      'companies:read',
      'companies:write',
      'agents:read',
      'groups:read',
      'conversations:read',
      'conversations:write',
      'solutions:read',
      'solutions:write',
      'analytics:read',
      'reports:read',
      'webhooks:read',
      'webhooks:write',
      'automations:read',
      'automations:write',
      'custom_fields:read',
      'custom_fields:write',
      'admin:read',
      'admin:write'
    ]
  },
  monday: {
    name: 'Monday.com',
    auth_url: 'https://auth.monday.com/oauth2/authorize',
    token_url: 'https://auth.monday.com/oauth2/token',
    scopes: [
      'boards:read',
      'boards:write',
      'items:read',
      'items:write',
      'updates:read',
      'updates:write',
      'notifications:read',
      'notifications:write',
      'account:read',
      'users:read',
      'tags:read',
      'tags:write',
      'forms:read',
      'forms:write',
      'documents:read',
      'documents:write',
      'workspaces:read',
      'admin:read',
      'me:read',
      'webhooks:read',
      'webhooks:write'
    ]
  },
  salesforce: {
    name: 'Salesforce',
    auth_url: 'https://login.salesforce.com/services/oauth2/authorize',
    token_url: 'https://login.salesforce.com/services/oauth2/token',
    scopes: [
      'api',
      'refresh_token',
      'full',
      'chatter_api',
      'visualforce',
      'lightning',
      'rest_api',
      'soap_api',
      'metadata',
      'custom_permissions',
      'app_access',
      'email',
      'offline_access',
      'profile',
      'user_management',
      'cdp_api',
      'marketing_cloud_api',
      'commerce_cloud_api',
      'service_cloud_api',
      'sales_cloud_api',
      'financial_cloud_api',
      'health_cloud_api',
      'education_cloud_api',
      'einstein_api',
      'analytics_api',
      'reporting_api',
      'dashboard_api',
      'web',
      'mobile_sdk'
    ]
  }
} as const;

// Webhook Event Types
export const WEBHOOK_EVENTS = {
  file: [
    'file.created',
    'file.updated',
    'file.deleted',
    'file.added'
  ],
  message: [
    'message.channels',
    'message.private',
    'message.added',
    'message.updated'
  ],
  project: [
    'project.created',
    'project.updated',
    'project.synced'
  ],
  deployment: [
    'deployment.created',
    'deployment.ready',
    'deployment.error',
    'deployment.updated'
  ],
  build: [
    'build.created',
    'build.ready',
    'build.error',
    'build.updated'
  ],
  issue: [
    'issue.created',
    'issue.updated',
    'issue.opened',
    'issue.closed',
    'issue.assigned',
    'issue.unassigned',
    'issue.priority_changed',
    'issue.label_added',
    'issue.label_removed'
  ],
  page: [
    'page.created',
    'page.updated',
    'page.deleted'
  ],
  pull_request: [
    'pull_request.opened',
    'pull_request.closed',
    'pull_request.updated'
  ],
  ticket: [
    'ticket.created',
    'ticket.updated',
    'ticket.deleted',
    'ticket.merged',
    'ticket.changed',
    'ticket.assigned',
    'ticket.unassigned'
  ],
  contact: [
    'contact.creation',
    'contact.deletion',
    'contact.propertyChange'
  ],
  company: [
    'company.creation',
    'company.deletion',
    'company.propertyChange'
  ],
  deal: [
    'deal.creation',
    'deal.deletion',
    'deal.propertyChange'
  ],
  organization: [
    'organization.created',
    'organization.updated',
    'organization.deleted'
  ],
  user: [
    'user.created',
    'user.updated',
    'user.deleted'
  ],
  group: [
    'group.created',
    'group.updated',
    'group.deleted'
  ],
  comment: [
    'comment.created',
    'comment.updated',
    'comment.deleted'
  ],
  satisfaction: [
    'satisfaction.created',
    'satisfaction.updated'
  ],
  freshdesk: [
    'ticket.created',
    'ticket.updated',
    'ticket.deleted',
    'ticket.status_changed',
    'ticket.priority_changed',
    'ticket.assigned',
    'ticket.unassigned',
    'ticket.reopened',
    'ticket.resolved',
    'ticket.closed',
    'contact.created',
    'contact.updated',
    'contact.deleted',
    'contact.merged',
    'company.created',
    'company.updated',
    'company.deleted',
    'agent.created',
    'agent.updated',
    'agent.deleted',
    'agent.status_changed',
    'group.created',
    'group.updated',
    'group.deleted',
    'conversation.created',
    'conversation.updated',
    'conversation.replied',
    'conversation.note_added',
    'solution.article.created',
    'solution.article.updated',
    'solution.article.published',
    'solution.article.deleted',
    'forum.topic.created',
    'forum.topic.updated',
    'forum.topic.deleted',
    'forum.post.created',
    'forum.post.updated',
    'survey.response.created',
    'survey.updated',
    'automation.rule.triggered',
    'automation.rule.completed',
    'scenario.executed',
    'custom_field.created',
    'custom_field.updated',
    'custom_field.deleted',
    'sla.breached',
    'escalation.triggered',
    'satisfaction.rating.updated',
    'feedback.received',
    'user.login',
    'user.logout',
    'data.exported',
    'data.imported'
  ],
  voice_call: [
    'voice-call.started',
    'voice-call.completed',
    'voice-call.missed'
  ],
  chat_conversation: [
    'chat.conversation.started',
    'chat.conversation.updated',
    'chat.conversation.ended'
  ],
  financial: [
    'invoice.created',
    'invoice.updated',
    'invoice.paid',
    'invoice.voided',
    'invoice.deleted',
    'contact.created',
    'contact.updated',
    'contact.deleted',
    'bank_transaction.created',
    'bank_transaction.updated',
    'bank_transaction.deleted',
    'payment.created',
    'payment.updated',
    'payment.deleted',
    'expense_claim.created',
    'expense_claim.updated',
    'expense_claim.approved',
    'expense_claim.paid',
    'journal.created',
    'journal.updated',
    'journal.posted'
  ],
  marketing: [
    'marketing.email',
    'marketing.email.sent',
    'subscription.change',
    'campaign.created',
    'campaign.updated'
  ],
  project_management: [
    'task.created',
    'task.updated',
    'task.completed',
    'task.assigned',
    'task.dependency_added',
    'project.created',
    'project.updated',
    'team.added',
    'story.created',
    'goal.created',
    'portfolio.updated'
  ],
  teams: [
    'message.created',
    'message.updated',
    'message.deleted',
    'channel.created',
    'channel.updated',
    'channel.deleted',
    'team.created',
    'team.updated',
    'team.deleted',
    'meeting.created',
    'meeting.updated',
    'meeting.started',
    'meeting.ended',
    'user.joined',
    'user.left',
    'presence.changed',
    'file.shared',
    'file.updated',
    'member.added',
    'member.removed',
    'app.installed',
    'app.uninstalled',
    'chat_thread.created',
    'chat_thread.updated',
    'call.started',
    'call.ended',
    'breakout_room.created',
    'breakout_room.updated',
    'breakout_room.deleted',
    'whiteboard.created',
    'whiteboard.updated',
    'poll.created',
    'poll.updated',
    'presentation.started',
    'presentation.ended',
    'transcription.completed',
    'recording.started',
    'recording.ended'
  ],
  data_management: [
    'table.records.created',
    'table.records.updated',
    'table.records.deleted',
    'base.created',
    'base.updated',
    'table.created',
    'base.shared',
    'collaborator.added',
    'collaborator.removed',
    'webhook.test',
    'automation.triggered',
    'script.executed',
    'form.response.created',
    'import.completed',
    'export.completed',
    'schema.changed',
    'field.updated',
    'view.created',
    'view.updated',
    'record.linked',
    'formula.computed',
    'automation.completed'
  ],
  microsoft365: [
    'message.created',
    'message.updated',
    'message.deleted',
    'channel.created',
    'channel.updated',
    'channel.deleted',
    'team.created',
    'team.updated',
    'team.deleted',
    'meeting.created',
    'meeting.updated',
    'meeting.started',
    'meeting.ended',
    'user.joined',
    'user.left',
    'presence.changed',
    'file.shared',
    'file.updated',
    'member.added',
    'member.removed',
    'calendar.event.created',
    'calendar.event.updated',
    'calendar.event.deleted',
    'document.created',
    'document.updated',
    'document.deleted',
    'site.created',
    'site.updated',
    'workflow.activated',
    'workflow.completed',
    'workflow.failed',
    'flow.triggered',
    'powerbi.report.updated',
    'app.installed',
    'app.uninstalled'
  ],
  monday: [
    'board.created',
    'board.updated',
    'board.deleted',
    'item.created',
    'item.updated',
    'item.deleted',
    'item.moved',
    'item.column_value_changed',
    'group.created',
    'group.updated',
    'group.deleted',
    'update.created',
    'update.updated',
    'update.deleted',
    'notification.created',
    'form.submitted',
    'automation.triggered',
    'automation.completed',
    'automation.failed',
    'file.uploaded',
    'file.deleted',
    'comment.created',
    'comment.updated',
    'comment.deleted',
    'user.added',
    'user.removed',
    'workspace.updated',
    'status.changed',
    'deadline.reached',
    'dependency.completed',
    'milestone.achieved'
  ],
  salesforce: [
    'account.created',
    'account.updated',
    'account.deleted',
    'contact.created',
    'contact.updated',
    'contact.deleted',
    'lead.created',
    'lead.updated',
    'lead.deleted',
    'lead.converted',
    'opportunity.created',
    'opportunity.updated',
    'opportunity.deleted',
    'opportunity.won',
    'opportunity.lost',
    'case.created',
    'case.updated',
    'case.deleted',
    'case.closed',
    'case.escalated',
    'campaign.created',
    'campaign.updated',
    'campaign.deleted',
    'campaign.started',
    'campaign.completed',
    'quote.created',
    'quote.updated',
    'quote.accepted',
    'quote.rejected',
    'order.created',
    'order.updated',
    'order.completed',
    'order.cancelled',
    'invoice.created',
    'invoice.updated',
    'invoice.paid',
    'invoice.overdue',
    'task.created',
    'task.updated',
    'task.completed',
    'event.created',
    'event.updated',
    'event.deleted',
    'call.created',
    'call.completed',
    'email.sent',
    'email.opened',
    'email.clicked',
    'meeting.scheduled',
    'meeting.completed',
    'workflow.triggered',
    'workflow.completed',
    'workflow.failed',
    'approval.requested',
    'approval.approved',
    'approval.rejected',
    'file.created',
    'file.deleted',
    'file.shared',
    'report.generated',
    'dashboard.updated',
    'subscription.created',
    'subscription.updated',
    'subscription.cancelled',
    'renewal.triggered',
    'renewal.completed',
    'escalation.created',
    'escalation.resolved',
    'notification.sent',
    'alert.triggered',
    'audit.log.created',
    'data.exported',
    'data.imported',
    'backup.created',
    'backup.completed',
    'user.login',
    'user.logout',
    'permission.changed',
    'role.changed',
    'api.limit.reached',
    'quota.exceeded',
    'system.maintenance',
    'integration.connected',
    'integration.disconnected',
    'sync.started',
    'sync.completed',
    'sync.failed',
    'duplicate.detected',
    'duplicate.merged',
    'field.updated',
    'record.restored',
    'record.archived',
    'batch.processed',
    'bulk.operation.completed',
    'custom.object.created',
    'custom.object.updated',
    'custom.object.deleted',
    'pricing.rule.activated',
    'pricing.rule.deactivated',
    'territory.assigned',
    'territory.changed',
    'forecast.updated',
    'pipeline.changed'
  ]
} as const;

// Integration Utilities
export const INTEGRATION_UTILS = {
  // Get integration by ID
  getById: (id: string) => {
    return ATOM_INTEGRATIONS.find(integration => integration.id === id);
  },
  
  // Get integrations by category
  getByCategory: (category: string) => {
    return ATOM_INTEGRATIONS.filter(integration => integration.category === category);
  },
  
  // Get integrations by status
  getByStatus: (status: string) => {
    return ATOM_INTEGRATIONS.filter(integration => integration.status === status);
  },
  
  // Get integrations by platform
  getByPlatform: (platform: string) => {
    return ATOM_INTEGRATIONS.filter(integration => 
      integration.platform === platform || integration.platform === 'web'
    );
  },
  
  // Get OAuth provider
  getOAuthProvider: (provider: string) => {
    return OAUTH_PROVIDERS[provider as keyof typeof OAUTH_PROVIDERS];
  },
  
  // Check if webhook is supported
  isWebhookSupported: (integrationId: string, event: string) => {
    const integration = INTEGRATION_UTILS.getById(integrationId);
    return integration?.webhooks?.includes(event) || false;
  },
  
  // Get integration limits
  getLimits: (integrationId: string) => {
    const integration = INTEGRATION_UTILS.getById(integrationId);
    return integration?.limits || {};
  },
  
  // Get total integrations count
  getTotalCount: () => ATOM_INTEGRATIONS.length,
  
  // Get completed integrations count
  getCompletedCount: () => ATOM_INTEGRATIONS.filter(i => i.status === 'complete').length,
  
  // Get categories with integrations
  getCategoriesWithIntegrations: () => {
    const categories = new Set(ATOM_INTEGRATIONS.map(i => i.category));
    return Array.from(categories);
  },
  
  // Get available features across all integrations
  getAvailableFeatures: () => {
    const features = new Set();
    ATOM_INTEGRATIONS.forEach(integration => {
      integration.features.forEach(feature => features.add(feature));
    });
    return Array.from(features);
  }
};

// Export default registry
export default INTEGRATION_UTILS;