"""add social media, financial, and menubar audit tables

Revision ID: 4ba6351c050c
Revises: da88b7d00bf2
Create Date: 2026-02-06 17:19:46.788916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4ba6351c050c'
down_revision: Union[str, Sequence[str], None] = 'da88b7d00bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('agent_execution_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('agent_maturity', sa.String(length=50), nullable=False),
    sa.Column('governance_check_passed', sa.Boolean(), nullable=False),
    sa.Column('required_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_granted', sa.Boolean(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_audit', schema=None) as batch_op:
        batch_op.create_index('ix_financial_audit_account', ['account_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_financial_audit_action', ['action_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_action_type'), ['action_type'], unique=False)
        batch_op.create_index('ix_financial_audit_agent', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_agent_execution_id'), ['agent_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_agent_maturity'), ['agent_maturity'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_governance_check_passed'), ['governance_check_passed'], unique=False)
        batch_op.create_index('ix_financial_audit_maturity', ['agent_maturity', 'governance_check_passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_success'), ['success'], unique=False)
        batch_op.create_index('ix_financial_audit_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_financial_audit_user', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_audit_user_id'), ['user_id'], unique=False)

    op.create_table('menu_bar_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('agent_execution_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('response_summary', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('agent_maturity', sa.String(length=50), nullable=True),
    sa.Column('governance_check_passed', sa.Boolean(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device_nodes.device_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_bar_audit', schema=None) as batch_op:
        batch_op.create_index('ix_menu_bar_audit_action', ['action', 'timestamp'], unique=False)
        batch_op.create_index('ix_menu_bar_audit_agent', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_agent_execution_id'), ['agent_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_agent_maturity'), ['agent_maturity'], unique=False)
        batch_op.create_index('ix_menu_bar_audit_device', ['device_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_governance_check_passed'), ['governance_check_passed'], unique=False)
        batch_op.create_index('ix_menu_bar_audit_maturity', ['agent_maturity', 'governance_check_passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_menu_bar_audit_user', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_user_id'), ['user_id'], unique=False)

    op.create_table('social_media_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('agent_execution_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('platform_response', sa.JSON(), nullable=True),
    sa.Column('agent_maturity', sa.String(length=50), nullable=False),
    sa.Column('governance_check_passed', sa.Boolean(), nullable=False),
    sa.Column('required_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_granted', sa.Boolean(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_media_audit', schema=None) as batch_op:
        batch_op.create_index('ix_social_media_audit_action', ['action_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_action_type'), ['action_type'], unique=False)
        batch_op.create_index('ix_social_media_audit_agent', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_agent_execution_id'), ['agent_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_agent_maturity'), ['agent_maturity'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_governance_check_passed'), ['governance_check_passed'], unique=False)
        batch_op.create_index('ix_social_media_audit_maturity', ['agent_maturity', 'governance_check_passed'], unique=False)
        batch_op.create_index('ix_social_media_audit_platform', ['platform', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_success'), ['success'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_social_media_audit_user', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_media_audit_user_id'), ['user_id'], unique=False)

    op.drop_table('sales_call_transcripts')
    op.drop_table('service_milestones')
    op.drop_table('service_projects')
    op.drop_table('service_tasks')
    op.drop_table('accounting_tax_nexus')
    op.drop_table('accounting_journal_entries')
    op.drop_table('accounting_budgets')
    with op.batch_alter_table('analytics_workflow_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_workflow_logs_execution_id')
        batch_op.drop_index('ix_analytics_workflow_logs_step_id')
        batch_op.drop_index('ix_analytics_workflow_logs_workflow_id')

    op.drop_table('analytics_workflow_logs')
    with op.batch_alter_table('accounting_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_accounting_transactions_external_id')

    op.drop_table('accounting_transactions')
    op.drop_table('accounting_categorization_proposals')
    op.drop_table('accounting_accounts')
    op.drop_table('service_appointments')
    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_leads_external_id')

    op.drop_table('sales_leads')
    op.drop_table('sales_follow_up_tasks')
    op.drop_table('accounting_invoices')
    op.drop_table('accounting_closes')
    op.drop_table('accounting_rules')
    op.drop_table('accounting_bills')
    with op.batch_alter_table('sales_deals', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_deals_external_id')

    op.drop_table('sales_deals')
    op.drop_table('accounting_documents')
    op.drop_table('accounting_entities')
    op.drop_table('service_contracts')
    op.drop_table('sales_commissions')
    with op.batch_alter_table('active_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index('ix_active_tokens_user', ['user_id', 'issued_at'], unique=False)

    with op.batch_alter_table('agent_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_proposals_proposal_type'), ['proposal_type'], unique=False)
        batch_op.create_index('ix_agent_proposals_proposed_by', ['proposed_by'], unique=False)

    with op.batch_alter_table('blocked_triggers', schema=None) as batch_op:
        batch_op.create_index('ix_blocked_triggers_agent', ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_triggers_agent_maturity_at_block'), ['agent_maturity_at_block'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_triggers_trigger_source'), ['trigger_source'], unique=False)

    with op.batch_alter_table('condition_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_condition_alerts_monitor', ['monitor_id', 'triggered_at'], unique=False)

    with op.batch_alter_table('episode_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_access_logs_accessed_by'), ['accessed_by'], unique=False)
        batch_op.create_index('ix_episode_access_logs_episode', ['episode_id'], unique=False)

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index('ix_episodes_agent_canvas', ['agent_id', 'canvas_action_count'], unique=False)
        batch_op.create_index('ix_episodes_session', ['session_id'], unique=False)
        batch_op.create_index('ix_episodes_started_at', ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('governance_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_governance_audit_logs_allowed')
        batch_op.create_index('ix_governance_audit_logs_allowed', ['allowed', 'checked_at'], unique=False)
        batch_op.create_index('ix_governance_audit_logs_action', ['action_type', 'checked_at'], unique=False)
        batch_op.create_index('ix_governance_audit_logs_agent', ['agent_id', 'checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_audit_logs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_audit_logs_agent_maturity'), ['agent_maturity'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_audit_logs_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index('ix_governance_audit_logs_maturity', ['agent_maturity', 'allowed'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_messages_next_run')
        batch_op.create_index('ix_scheduled_messages_next_run', ['next_run', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_scheduled_messages_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_status'), ['status'], unique=False)

    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_security_audit_log_severity_timestamp', ['severity', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_audit_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('social_post_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.create_index('ix_social_post_history_job_id', ['job_id'], unique=False)

    with op.batch_alter_table('supervision_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervision_sessions_agent_id'), ['agent_id'], unique=False)

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_training_sessions_agent', ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_proposal_id'), ['proposal_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_training_sessions_supervisor_id'), ['supervisor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_training_sessions_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_training_sessions_created_at'))
        batch_op.drop_index('ix_training_sessions_agent')

    with op.batch_alter_table('supervision_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervision_sessions_agent_id'))

    with op.batch_alter_table('social_post_history', schema=None) as batch_op:
        batch_op.drop_index('ix_social_post_history_job_id')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_audit_log_timestamp'))
        batch_op.drop_index('ix_security_audit_log_severity_timestamp')

    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_created_at'))
        batch_op.drop_index('ix_scheduled_messages_created')
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_agent_id'))
        batch_op.drop_index('ix_scheduled_messages_next_run')
        batch_op.create_index('ix_scheduled_messages_next_run', ['next_run'], unique=False)

    with op.batch_alter_table('governance_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_governance_audit_logs_request_id'))
        batch_op.drop_index('ix_governance_audit_logs_maturity')
        batch_op.drop_index(batch_op.f('ix_governance_audit_logs_checked_at'))
        batch_op.drop_index(batch_op.f('ix_governance_audit_logs_agent_maturity'))
        batch_op.drop_index(batch_op.f('ix_governance_audit_logs_agent_id'))
        batch_op.drop_index('ix_governance_audit_logs_agent')
        batch_op.drop_index('ix_governance_audit_logs_action')
        batch_op.drop_index('ix_governance_audit_logs_allowed')
        batch_op.create_index('ix_governance_audit_logs_allowed', ['allowed'], unique=False)

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_user_id'))
        batch_op.drop_index('ix_episodes_started_at')
        batch_op.drop_index('ix_episodes_session')
        batch_op.drop_index('ix_episodes_agent_canvas')

    with op.batch_alter_table('episode_access_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_episode_access_logs_episode')
        batch_op.drop_index(batch_op.f('ix_episode_access_logs_accessed_by'))

    with op.batch_alter_table('condition_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_condition_alerts_monitor')

    with op.batch_alter_table('blocked_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_triggers_trigger_source'))
        batch_op.drop_index(batch_op.f('ix_blocked_triggers_agent_maturity_at_block'))
        batch_op.drop_index('ix_blocked_triggers_agent')

    with op.batch_alter_table('agent_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_proposals_proposed_by')
        batch_op.drop_index(batch_op.f('ix_agent_proposals_proposal_type'))

    with op.batch_alter_table('active_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_active_tokens_user')
        batch_op.drop_index(batch_op.f('ix_active_tokens_expires_at'))

    op.create_table('sales_commissions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.VARCHAR(), nullable=False),
    sa.Column('invoice_id', sa.VARCHAR(), nullable=True),
    sa.Column('payee_id', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('calculated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['sales_deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_contracts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.VARCHAR(), nullable=True),
    sa.Column('product_service_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=13), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['sales_deals.id'], ),
    sa.ForeignKeyConstraint(['product_service_id'], ['business_product_services.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_entities',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('tax_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_documents',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(), nullable=True),
    sa.Column('bill_id', sa.VARCHAR(), nullable=True),
    sa.Column('invoice_id', sa.VARCHAR(), nullable=True),
    sa.Column('extracted_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['accounting_bills.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['accounting_invoices.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_deals',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('stage', sa.VARCHAR(length=13), nullable=True),
    sa.Column('probability', sa.FLOAT(), nullable=True),
    sa.Column('health_score', sa.FLOAT(), nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), nullable=True),
    sa.Column('last_engagement_at', sa.DATETIME(), nullable=True),
    sa.Column('negotiation_state', sa.VARCHAR(length=10), nullable=True),
    sa.Column('last_followup_at', sa.DATETIME(), nullable=True),
    sa.Column('followup_count', sa.INTEGER(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_deals', schema=None) as batch_op:
        batch_op.create_index('ix_sales_deals_external_id', ['external_id'], unique=False)

    op.create_table('accounting_bills',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), nullable=False),
    sa.Column('bill_number', sa.VARCHAR(), nullable=True),
    sa.Column('issue_date', sa.DATETIME(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=5), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('milestone_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['service_milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['service_projects.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting_transactions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['accounting_entities.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_rules',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('merchant_pattern', sa.VARCHAR(), nullable=False),
    sa.Column('target_account_id', sa.VARCHAR(), nullable=False),
    sa.Column('confidence_weight', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'merchant_pattern', name='_workspace_merchant_uc')
    )
    op.create_table('accounting_closes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('period', sa.VARCHAR(), nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_by', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_invoices',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(), nullable=True),
    sa.Column('issue_date', sa.DATETIME(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['accounting_entities.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting_transactions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_follow_up_tasks',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('suggested_date', sa.DATETIME(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('ai_rationale', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['sales_deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_leads',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=12), nullable=True),
    sa.Column('ai_score', sa.FLOAT(), nullable=True),
    sa.Column('ai_qualification_summary', sa.TEXT(), nullable=True),
    sa.Column('is_spam', sa.BOOLEAN(), nullable=True),
    sa.Column('is_converted', sa.BOOLEAN(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.create_index('ix_sales_leads_external_id', ['external_id'], unique=False)

    op.create_table('service_appointments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), nullable=False),
    sa.Column('service_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('deposit_amount', sa.FLOAT(), nullable=True),
    sa.Column('is_deposit_paid', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['accounting_entities.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business_product_services.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_accounts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('standards_mapping', sqlite.JSON(), nullable=True),
    sa.Column('last_audit_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'code', name='_workspace_code_uc')
    )
    op.create_table('accounting_categorization_proposals',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('suggested_account_id', sa.VARCHAR(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('reasoning', sa.TEXT(), nullable=True),
    sa.Column('is_accepted', sa.BOOLEAN(), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['suggested_account_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_transactions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('transaction_date', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('is_intercompany', sa.BOOLEAN(), nullable=True),
    sa.Column('counterparty_workspace_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('milestone_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_workspace_id'], ['workspaces.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['service_milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['service_projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_accounting_transactions_external_id', ['external_id'], unique=False)

    op.create_table('analytics_workflow_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('execution_id', sa.VARCHAR(), nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(), nullable=False),
    sa.Column('step_id', sa.VARCHAR(), nullable=False),
    sa.Column('step_type', sa.VARCHAR(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('duration_ms', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('error_code', sa.VARCHAR(), nullable=True),
    sa.Column('trigger_data', sqlite.JSON(), nullable=True),
    sa.Column('results', sqlite.JSON(), nullable=True),
    sa.Column('meta_info', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_workflow_logs', schema=None) as batch_op:
        batch_op.create_index('ix_analytics_workflow_logs_workflow_id', ['workflow_id'], unique=False)
        batch_op.create_index('ix_analytics_workflow_logs_step_id', ['step_id'], unique=False)
        batch_op.create_index('ix_analytics_workflow_logs_execution_id', ['execution_id'], unique=False)

    op.create_table('accounting_budgets',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('category_id', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('period', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_journal_entries',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['accounting_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_tax_nexus',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('region', sa.VARCHAR(), nullable=False),
    sa.Column('tax_type', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_tasks',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('milestone_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('actual_hours', sa.FLOAT(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['service_milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['service_projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_projects',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=14), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('budget_hours', sa.FLOAT(), nullable=True),
    sa.Column('actual_hours', sa.FLOAT(), nullable=True),
    sa.Column('budget_amount', sa.FLOAT(), nullable=True),
    sa.Column('actual_burn', sa.FLOAT(), nullable=True),
    sa.Column('budget_status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('project_type', sa.VARCHAR(), nullable=True),
    sa.Column('planned_start_date', sa.DATETIME(), nullable=True),
    sa.Column('planned_end_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_start_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_end_date', sa.DATETIME(), nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), nullable=True),
    sa.Column('predicted_end_date', sa.DATETIME(), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=True),
    sa.Column('risk_rationale', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['service_contracts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_milestones',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('actual_burn', sa.FLOAT(), nullable=True),
    sa.Column('budget_status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('planned_start_date', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('invoice_id', sa.VARCHAR(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['service_projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_call_transcripts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), nullable=False),
    sa.Column('deal_id', sa.VARCHAR(), nullable=True),
    sa.Column('meeting_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('raw_transcript', sa.TEXT(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('objections', sqlite.JSON(), nullable=True),
    sa.Column('action_items', sqlite.JSON(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['sales_deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_media_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_media_audit_user_id'))
        batch_op.drop_index('ix_social_media_audit_user')
        batch_op.drop_index(batch_op.f('ix_social_media_audit_timestamp'))
        batch_op.drop_index(batch_op.f('ix_social_media_audit_success'))
        batch_op.drop_index(batch_op.f('ix_social_media_audit_request_id'))
        batch_op.drop_index(batch_op.f('ix_social_media_audit_post_id'))
        batch_op.drop_index('ix_social_media_audit_platform')
        batch_op.drop_index('ix_social_media_audit_maturity')
        batch_op.drop_index(batch_op.f('ix_social_media_audit_governance_check_passed'))
        batch_op.drop_index(batch_op.f('ix_social_media_audit_agent_maturity'))
        batch_op.drop_index(batch_op.f('ix_social_media_audit_agent_id'))
        batch_op.drop_index(batch_op.f('ix_social_media_audit_agent_execution_id'))
        batch_op.drop_index('ix_social_media_audit_agent')
        batch_op.drop_index(batch_op.f('ix_social_media_audit_action_type'))
        batch_op.drop_index('ix_social_media_audit_action')

    op.drop_table('social_media_audit')
    with op.batch_alter_table('menu_bar_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_user_id'))
        batch_op.drop_index('ix_menu_bar_audit_user')
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_timestamp'))
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_success'))
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_request_id'))
        batch_op.drop_index('ix_menu_bar_audit_maturity')
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_governance_check_passed'))
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_device_id'))
        batch_op.drop_index('ix_menu_bar_audit_device')
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_agent_maturity'))
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_agent_id'))
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_agent_execution_id'))
        batch_op.drop_index('ix_menu_bar_audit_agent')
        batch_op.drop_index('ix_menu_bar_audit_action')

    op.drop_table('menu_bar_audit')
    with op.batch_alter_table('financial_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_audit_user_id'))
        batch_op.drop_index('ix_financial_audit_user')
        batch_op.drop_index('ix_financial_audit_timestamp')
        batch_op.drop_index(batch_op.f('ix_financial_audit_success'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_request_id'))
        batch_op.drop_index('ix_financial_audit_maturity')
        batch_op.drop_index(batch_op.f('ix_financial_audit_governance_check_passed'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_agent_maturity'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_agent_id'))
        batch_op.drop_index(batch_op.f('ix_financial_audit_agent_execution_id'))
        batch_op.drop_index('ix_financial_audit_agent')
        batch_op.drop_index(batch_op.f('ix_financial_audit_action_type'))
        batch_op.drop_index('ix_financial_audit_action')
        batch_op.drop_index(batch_op.f('ix_financial_audit_account_id'))
        batch_op.drop_index('ix_financial_audit_account')

    op.drop_table('financial_audit')
    # ### end Alembic commands ###
