"""add missing database relationships for audit models

Revision ID: a04bed1462ee
Revises: 4ba6351c050c
Create Date: 2026-02-06 17:33:30.947624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04bed1462ee'
down_revision: Union[str, Sequence[str], None] = '4ba6351c050c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('governance_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_governance_audit_logs_allowed')
        batch_op.create_index(batch_op.f('ix_governance_audit_logs_allowed'), ['allowed'], unique=False)

    with op.batch_alter_table('menu_bar_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_menu_bar_audit_action')
        batch_op.create_index(batch_op.f('ix_menu_bar_audit_action'), ['action'], unique=False)

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_revoked_tokens_jti')
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_messages_platform')
        batch_op.create_index(batch_op.f('ix_scheduled_messages_platform'), ['platform'], unique=False)

    with op.batch_alter_table('social_media_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_social_media_audit_platform')
        batch_op.create_index(batch_op.f('ix_social_media_audit_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_media_audit_platform'))
        batch_op.create_index('ix_social_media_audit_platform', ['platform', 'timestamp'], unique=False)

    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_platform'))
        batch_op.create_index('ix_scheduled_messages_platform', ['platform', 'status'], unique=False)

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.create_index('ix_revoked_tokens_jti', ['jti'], unique=False)

    with op.batch_alter_table('menu_bar_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_bar_audit_action'))
        batch_op.create_index('ix_menu_bar_audit_action', ['action', 'timestamp'], unique=False)

    with op.batch_alter_table('governance_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_audit_logs_allowed'))
        batch_op.create_index('ix_governance_audit_logs_allowed', ['allowed', 'checked_at'], unique=False)

    # ### end Alembic commands ###
