import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { X, ExternalLink, RefreshCw, Check, AlertCircle } from "lucide-react";
import { marked } from "marked";

interface CanvasHostProps {
    lastMessage: any;
}

interface CanvasState {
    visible: boolean;
    component: string;
    title?: string;
    data: any;
}

export function CanvasHost({ lastMessage }: CanvasHostProps) {
    const [state, setState] = useState<CanvasState | null>(null);

    useEffect(() => {
        if (!lastMessage) return;

        // Check for canvas event type (websocket message structure might vary)
        // Upstream useWebSocket might return raw event or parsed data. 
        // Assuming parsed JSON as per ChatInterface.tsx usage (msg.type)
        const msg = lastMessage;

        if (msg.type === "canvas:update") {
            const { action, component, data, title } = msg.data || msg;

            if (action === "close") {
                setState(null);
            } else if (action === "present" || action === "update") {
                setState({
                    visible: true,
                    component: component || "markdown",
                    title,
                    data,
                });
            }
        }
    }, [lastMessage]);

    if (!state || !state.visible) return null;

    return (
        <div className="absolute top-4 right-4 bottom-4 w-[400px] bg-background border shadow-xl z-50 rounded-lg flex flex-col animate-in slide-in-from-right-10 overflow-hidden">
            <div className="flex items-center justify-between p-4 border-b bg-muted/40">
                <h3 className="font-semibold text-sm truncate pr-2">{state.title || "Agent Canvas"}</h3>
                <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setState(null)}>
                    <X className="h-4 w-4" />
                </Button>
            </div>

            <div className="flex-1 overflow-auto p-4">
                <CanvasContent component={state.component} data={state.data} />
            </div>

            <div className="p-2 border-t bg-muted/10 text-[10px] text-muted-foreground text-center">
                Generated by Atom AI
            </div>
        </div>
    );
}

function CanvasContent({ component, data }: { component: string; data: any }) {
    if (!data) return <div className="text-muted-foreground p-4">No data to display</div>;

    switch (component) {
        case "markdown":
            return (
                <div
                    className="prose dark:prose-invert max-w-none text-sm prose-p:leading-relaxed prose-pre:bg-muted"
                    dangerouslySetInnerHTML={{ __html: marked.parse(typeof data === 'string' ? data : data.content || '') }}
                />
            );

        case "status_panel":
            return (
                <div className="space-y-4">
                    {data.items?.map((item: any, i: number) => (
                        <Card key={i} className="bg-card/50">
                            <CardContent className="p-4 flex items-center justify-between">
                                <span className="text-sm font-medium">{item.label}</span>
                                <div className="flex items-center gap-2">
                                    <span className="text-lg font-bold">{item.value}</span>
                                    {item.trend && (
                                        <span className={`text-xs ${item.trend > 0 ? 'text-green-500' : 'text-red-500'}`}>
                                            {item.trend > 0 ? '↑' : '↓'} {Math.abs(item.trend)}%
                                        </span>
                                    )}
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            );

        case "form":
            return (
                <div className="space-y-4">
                    {data.fields?.map((field: any, i: number) => (
                        <div key={i} className="space-y-2">
                            <label className="text-xs font-medium">{field.label}</label>
                            <input
                                type={field.type || "text"}
                                className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
                                placeholder={field.placeholder}
                                defaultValue={field.defaultValue}
                            />
                        </div>
                    ))}
                    <Button className="w-full mt-2">Submit</Button>
                </div>
            );

        default:
            return (
                <div className="p-4 border rounded-md border-dashed">
                    <p className="text-sm font-medium mb-2">Component: {component}</p>
                    <pre className="text-xs overflow-auto bg-muted p-2 rounded">
                        {JSON.stringify(data, null, 2)}
                    </pre>
                </div>
            );
    }
}
