import React, { useState, useEffect, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { X, ExternalLink, RefreshCw, Check, AlertCircle, Code, Camera, Globe, Play, Layers } from "lucide-react";
import { marked } from "marked";
import { renderMarkdownSafe } from "@/lib/sanitize";
import { LineChartCanvas } from "../canvas/LineChart";
import { BarChartCanvas } from "../canvas/BarChart";
import { PieChartCanvas } from "../canvas/PieChart";
import { InteractiveForm } from "../canvas/InteractiveForm";
import { useCanvasStateRegistration } from "@/hooks/useCanvasStateRegistration";

interface CanvasHostProps {
    lastMessage: any;
}

interface CanvasState {
    visible: boolean;
    component: "markdown" | "chart" | "form" | "status_panel" | "line_chart" | "bar_chart" | "pie_chart" | "eval" | "snapshot" | "browser_view" | "office_preview" | "custom";
    title?: string;
    data: any;
}

export function CanvasHost({ lastMessage }: CanvasHostProps) {
    const [state, setState] = useState<CanvasState | null>(null);
    const [canvasId] = useState(() => `canvas_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`);

    useEffect(() => {
        if (!lastMessage) return;

        const msg = lastMessage;

        // Support both message patterns
        if (msg.type === "canvas:update" || msg.type === "canvas:present") {
            const { action, component, data, title } = msg.data || msg;

            if (action === "close") {
                setState(null);
            } else if (action === "present" || action === "update") {
                setState({
                    visible: true,
                    component: component || "markdown",
                    title,
                    data,
                });
            }
        }
    }, [lastMessage]);

    if (!state || !state.visible) return null;

    // ─── AI Accessibility: register canvas state for agent read-back ───
    const officeState = useMemo(() => {
        if (state.component === "office_preview") {
            return {
                type: "generic" as const,
                component: "office" as const,
                title: state.title || "Office Document",
                fileType: (state.data as any)?.fileType || (state.data as any)?.ext || "xlsx",
                filePath: (state.data as any)?.filePath || (state.data as any)?.file_path || "",
                html: typeof state.data === "string" ? state.data : (state.data as any)?.html || "",
            };
        }
        if (state.component === "markdown") {
            return {
                type: "generic" as const,
                component: "markdown" as const,
                title: state.title || "Markdown",
                text: typeof state.data === "string" ? state.data : JSON.stringify(state.data),
                html: typeof state.data === "string" ? renderMarkdownSafe(state.data) : "",
            };
        }
        return {
            type: "generic" as const,
            component: state.component,
            title: state.title || "Canvas",
            data: state.data,
        };
    }, [state]);

    useCanvasStateRegistration(canvasId, officeState as any);

    return (
        <div className="absolute top-4 right-4 bottom-4 w-[450px] bg-background border shadow-xl z-50 rounded-lg flex flex-col animate-in slide-in-from-right-10 overflow-hidden ring-1 ring-border/50">
            <div className="flex items-center justify-between p-4 border-b bg-muted/40">
                <div className="flex items-center gap-2">
                    <CanvasIcon component={state.component} />
                    <h3 className="font-semibold text-sm truncate max-w-[300px]">{state.title || "Agent Canvas"}</h3>
                </div>
                <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setState(null)}>
                    <X className="h-4 w-4" />
                </Button>
            </div>

            <div className="flex-1 overflow-auto p-4 custom-scrollbar">
                <CanvasContent component={state.component} data={state.data} canvasId={canvasId} />
            </div>

            <div className="p-2 border-t bg-muted/10 text-[10px] text-muted-foreground text-center">
                Generated by Atom AI
            </div>
        </div>
    );
}

function CanvasIcon({ component }: { component: string }) {
    switch (component) {
        case "eval": return <Code className="h-4 w-4 text-blue-500" />;
        case "snapshot": return <Camera className="h-4 w-4 text-purple-500" />;
        case "browser_view": return <Globe className="h-4 w-4 text-green-500" />;
        case "markdown": return <ExternalLink className="h-4 w-4 text-primary" />;
        case "status_panel": return <Check className="h-4 w-4 text-green-500" />;
        default: return <Layers className="h-4 w-4 text-primary" />;
    }
}

function CanvasContent({ component, data, canvasId }: { component: string; data: any; canvasId: string }) {
    if (!data) return <div className="text-muted-foreground p-4">No data to display</div>;

    switch (component) {
        case "markdown":
            return (
                <div
                    className="prose dark:prose-invert max-w-none text-sm prose-p:leading-relaxed prose-pre:bg-muted"
                    dangerouslySetInnerHTML={{ __html: renderMarkdownSafe(typeof data === 'string' ? data : data.content || '') }}
                />
            );

        case "eval":
            return (
                <div className="space-y-4">
                    <div className="bg-zinc-950 rounded-lg p-4 font-mono text-xs overflow-auto border border-zinc-800 shadow-inner">
                        <div className="flex justify-between items-center mb-2 border-b border-zinc-800 pb-2">
                            <span className="text-zinc-500">javascript</span>
                            <Button variant="ghost" size="sm" className="h-6 text-[10px] text-zinc-400 hover:text-gray-900 dark:text-white">
                                <Play className="h-3 w-3 mr-1" /> Run
                            </Button>
                        </div>
                        <pre className="text-blue-400">{data.code || data}</pre>
                    </div>
                    {data.output && (
                        <div className="bg-muted/50 rounded-lg p-3 border">
                            <p className="text-[10px] font-bold uppercase text-muted-foreground mb-1">Output</p>
                            <pre className="text-xs">{typeof data.output === 'string' ? data.output : JSON.stringify(data.output, null, 2)}</pre>
                        </div>
                    )}
                </div>
            );

        case "snapshot":
            return (
                <div className="space-y-4">
                    <div className="flex flex-wrap gap-2 mb-4">
                        {data.timestamp && (
                            <span className="px-2 py-1 rounded-md bg-muted text-[10px] text-muted-foreground border">
                                Captured: {new Date(data.timestamp).toLocaleTimeString()}
                            </span>
                        )}
                        {data.source && (
                            <span className="px-2 py-1 rounded-md bg-primary/10 text-[10px] text-primary border border-primary/20">
                                Source: {data.source}
                            </span>
                        )}
                    </div>
                    <div className="border rounded-lg overflow-hidden bg-card">
                        <div className="p-2 border-b bg-muted/20 flex justify-between items-center">
                            <span className="text-[10px] font-medium text-muted-foreground uppercase tracking-wider">State Tree</span>
                        </div>
                        <pre className="p-4 text-[11px] overflow-auto max-h-[400px] bg-muted/5 font-mono">
                            {JSON.stringify(data.state || data, null, 2)}
                        </pre>
                    </div>
                </div>
            );

        case "browser_view":
            return (
                <div className="space-y-4">
                    <div className="flex items-center gap-2 p-2 bg-muted/30 rounded-lg border text-xs">
                        <Globe className="h-3 w-3 text-muted-foreground" />
                        <span className="truncate flex-1 text-muted-foreground italic">{data.url || "about:blank"}</span>
                    </div>
                    {data.screenshot ? (
                        <div className="border rounded-lg overflow-hidden shadow-sm relative group">
                            <img
                                src={data.screenshot.startsWith('data:') ? data.screenshot : `data:image/png;base64,${data.screenshot}`}
                                alt="Browser Snapshot"
                                className="w-full h-auto cursor-zoom-in"
                            />
                            <div className="absolute inset-x-0 bottom-0 bg-black/10 dark:bg-black/60 backdrop-blur-sm p-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                <p className="text-[10px] text-gray-900 dark:text-white text-center">Interactive remote control disabled in preview</p>
                            </div>
                        </div>
                    ) : (
                        <div className="h-[300px] border border-dashed rounded-lg flex flex-col items-center justify-center text-muted-foreground">
                            <Globe className="h-8 w-8 mb-2 opacity-20" />
                            <p className="text-xs">Connecting to remote browser...</p>
                        </div>
                    )}
                </div>
            );

        case "status_panel":
            return (
                <div className="space-y-4">
                    {data.items?.map((item: any, i: number) => (
                        <Card key={i} className="bg-card/50">
                            <CardContent className="p-4 flex items-center justify-between">
                                <span className="text-sm font-medium">{item.label}</span>
                                <div className="flex items-center gap-2">
                                    <span className="text-lg font-bold">{item.value}</span>
                                    {item.trend && (
                                        <span className={`text-xs ${item.trend > 0 ? 'text-green-500' : 'text-red-500'}`}>
                                            {item.trend > 0 ? '↑' : '↓'} {Math.abs(item.trend)}%
                                        </span>
                                    )}
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            );

        case "form":
            return (
                <InteractiveForm
                    fields={data.fields}
                    title={data.title}
                    submitLabel={data.submitLabel}
                    canvasId={canvasId}
                    onSubmit={async (formData) => {
                        try {
                            const { apiClient } = await import('../../lib/api-client');
                            const response = await apiClient.post("/api/canvas/submit", {
                                canvas_id: canvasId,
                                form_data: formData
                            });
                            if (!(response as any).data.success) {
                                throw new Error('Submission failed');
                            }
                        } catch (error) {
                            console.error('Form submission error:', error);
                            throw error;
                        }
                    }}
                />
            );

        case "line_chart":
            return <LineChartCanvas data={data.data} title={data.title} color={data.color} />;

        case "bar_chart":
            return <BarChartCanvas data={data.data} title={data.title} color={data.color} />;

        case "pie_chart":
            return <PieChartCanvas data={data.data} title={data.title} />;

        case "office_preview":
            return <OfficePreviewCanvas data={data} canvasId={canvasId} />;

        default:
            return (
                <div className="p-4 border rounded-md border-dashed">
                    <p className="text-sm font-medium mb-2">Component: {component}</p>
                    <pre className="text-xs overflow-auto bg-muted p-2 rounded">
                        {JSON.stringify(data, null, 2)}
                    </pre>
                </div>
            );
    }
}

function OfficePreviewCanvas({ data, canvasId }: { data: any; canvasId: string }) {
    const [editableContent, setEditableContent] = useState(data.html || "");

    useEffect(() => {
        setEditableContent(data.html || "");
    }, [data.html]);

    const handleBlur = async (e: React.FocusEvent<HTMLDivElement>) => {
        const textVal = e.currentTarget.textContent || "";
        try {
            await fetch("/api/v1/office/sync-update", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    canvas_id: canvasId,
                    file_path: data.file_path,
                    user_id: "user_coedit",
                    edit_type: "document",
                    data: { content: textVal }
                })
            });
        } catch (err) {
            console.error("Office co-edit sync failed:", err);
        }
    };

    return (
        <div className="space-y-4">
            <div className="flex items-center justify-between gap-2 p-2 bg-muted/30 rounded-lg border text-xs">
                <span className="truncate flex-1 text-muted-foreground font-medium">{data.file_path || "Office Document"}</span>
                <span className="text-[10px] text-green-600 bg-green-500/10 px-2 py-0.5 rounded border border-green-500/20 font-semibold">Co-Editing Active</span>
            </div>
            {data.html ? (
                <div 
                    contentEditable
                    suppressContentEditableWarning
                    onBlur={handleBlur}
                    className="border rounded-lg p-4 bg-card overflow-auto max-h-[500px] prose dark:prose-invert max-w-none text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
                    dangerouslySetInnerHTML={{ __html: renderMarkdownSafe(editableContent) }}
                />
            ) : (
                <div className="h-[200px] border border-dashed rounded-lg flex flex-col items-center justify-center text-muted-foreground">
                    <Layers className="h-8 w-8 mb-2 opacity-20" />
                    <p className="text-xs">No preview content available</p>
                </div>
            )}
        </div>
    );
}
