#!/usr/bin/env bash
set -euo pipefail

# Atom Quick Start Script
# Run: ./scripts/quickstart.sh   (or: make setup)
# Sets up a complete Atom dev environment from scratch.

cd "$(dirname "$0")/.."

echo "🚀 Atom Quick Start"
echo "===================="

# Check prerequisites
for cmd in python3 node npm git make; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "❌ '$cmd' is required but not installed"; exit 1; }
done

# Node >= 20.9 is required by Next.js 16 (the frontend framework).
if [ "$(node -e 'const [ma,mi]=process.versions.node.split(".").map(Number); console.log(ma>20||(ma===20&&mi>=9)?1:0)')" != "1" ]; then
    echo "❌ Node.js 20.9+ required (found $(node --version))"
    exit 1
fi
echo "✅ Node $(node --version)"

PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
if python3 -c 'import sys; assert sys.version_info >= (3,11)' 2>/dev/null; then
    echo "✅ Python $PY_VERSION"
else
    echo "❌ Python 3.11+ required (found $PY_VERSION)"
    exit 1
fi

# --- Backend setup ---
echo ""
echo "📦 Setting up backend..."

if [ ! -d "backend/venv" ]; then
    python3 -m venv backend/venv
fi
source backend/venv/bin/activate
pip install -q -r backend/requirements.txt
echo "✅ Backend dependencies installed"

# --- Generate .env if missing ---
if [ ! -f "backend/.env" ]; then
    echo ""
    echo "🔧 Generating .env with secure defaults..."

    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    BYOK_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")

    cat > backend/.env <<EOF
# Auto-generated by quickstart.sh
SECRET_KEY=$SECRET_KEY
JWT_SECRET_KEY=$JWT_SECRET
BYOK_ENCRYPTION_KEY=$BYOK_KEY
DATABASE_URL=sqlite:///./atom_dev.db
ENVIRONMENT=development

# Add your LLM API key here (at least one required for AI features):
# OPENAI_API_KEY=sk-your-key-here
# ANTHROPIC_API_KEY=sk-ant-your-key-here
# DEEPSEEK_API_KEY=sk-your-key-here

# Or use a local model (no API key needed):
# ATOM_LOCAL_ONLY=true
# OLLAMA_BASE_URL=http://localhost:11434/v1
EOF
    echo "✅ Generated backend/.env"
    echo "⚠️  Edit backend/.env to add your API key, or set ATOM_LOCAL_ONLY=true for Ollama"
else
    echo "✅ backend/.env already exists"
fi

# --- Frontend setup ---
echo ""
echo "📦 Setting up frontend..."

cd frontend-nextjs
npm install --legacy-peer-deps

# Point the frontend at the local backend (only if no .env.local yet)
if [ ! -f ".env.local" ]; then
    cat > .env.local <<EOF
NEXT_PUBLIC_API_URL=http://localhost:8001
EOF
    echo "✅ Generated frontend-nextjs/.env.local"
fi
echo "✅ Frontend dependencies installed"
cd ..

# --- Check for Ollama ---
echo ""
if command -v ollama >/dev/null 2>&1; then
    echo "🦙 Ollama detected! You can run Atom fully local."
    echo "   To use: set ATOM_LOCAL_ONLY=true in backend/.env"
    echo "   Ollama will serve as the LLM backend (no API key needed)."
else
    echo "💡 Tip: Install Ollama (https://ollama.ai) for free local AI."
    echo "   Then set ATOM_LOCAL_ONLY=true in backend/.env"
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Edit backend/.env — add an API key or set ATOM_LOCAL_ONLY=true"
echo "  2. Run: ./scripts/dev.sh   (or: make dev)"
echo "  3. Open http://localhost:3001"
echo ""
echo "On first backend startup, the admin password is generated and saved to"
echo "backend/logs/bootstrap_admin_password.txt (sign in as admin@example.com)."
