#!/usr/bin/env bash
set -euo pipefail

# Atom Quick Start Script
# Run: curl -fsSL https://raw.githubusercontent.com/rush86999/atom/main/scripts/quickstart.sh | bash
# Or:  ./scripts/quickstart.sh

# Run: ./scripts/quickstart.sh
# Sets up a complete Atom dev environment from scratch.

set -euo pipefail
cd "$(dirname "$0")/.."

echo "🚀 Atom Quick Start"
echo "===================="

# Check prerequisites
command -v python3 >/dev/null 2>&1 || { echo "❌ Python 3.11+ is required"; exit 1; }
command -v node >/dev/null 2>&1 || { echo "❌ Node.js 18+ is required"; exit 1; }

PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
if python3 -c 'import sys; assert sys.version_info >= (3,11)' 2>/dev/null; then
    echo "✅ Python $PY_VERSION"
else
    echo "❌ Python 3.11+ required (found $PY_VERSION)"
    exit 1
fi
echo "✅ Node $(node --version)"

# --- Backend setup ---
echo ""
echo "📦 Setting up backend..."

if [ ! -d "backend/venv" ]; then
    python3 -m venv backend/venv
fi
source backend/venv/bin/activate
pip install -q -r backend/requirements.txt 2>/dev/null || pip install -q -r backend/requirements.txt
echo "✅ Backend dependencies installed"

# --- Generate .env if missing ---
if [ ! -f "backend/.env" ]; then
    echo ""
    echo "🔧 Generating .env with secure defaults..."

    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    BYOK_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")

    cat > backend/.env <<EOF
# Auto-generated by quickstart.sh
SECRET_KEY=$SECRET_KEY
JWT_SECRET_KEY=$JWT_SECRET
BYOK_ENCRYPTION_KEY=$BYOK_KEY
DATABASE_URL=sqlite:///./atom_dev.db
ENVIRONMENT=development

# Add your LLM API key here (at least one required for AI features):
# OPENAI_API_KEY=sk-your-key-here
# ANTHROPIC_API_KEY=sk-ant-your-key-here
# DEEPSEEK_API_KEY=sk-your-key-here

# Or use a local model (no API key needed):
# ATOM_LOCAL_ONLY=true
# OLLAMA_BASE_URL=http://localhost:11434/v1
EOF
    echo "✅ Generated backend/.env"
    echo "⚠️  Edit backend/.env to add your API key, or set ATOM_LOCAL_ONLY=true for Ollama"
else
    echo "✅ backend/.env already exists"
fi

# --- Frontend setup ---
echo ""
echo "📦 Setting up frontend..."

cd frontend-nextjs
npm install --legacy-peer-deps 2>/dev/null
echo "✅ Frontend dependencies installed"
cd ..

# --- Check for Ollama ---
echo ""
if command -v ollama >/dev/null 2>&1; then
    echo "🦙 Ollama detected! You can run Atom fully local."
    echo "   To use: set ATOM_LOCAL_ONLY=true in backend/.env"
    echo "   Then: ./scripts/dev.sh"
    echo "   Ollama will serve as the LLM backend (no API key needed)."
else
    echo "💡 Tip: Install Ollama (https://ollama.ai) for free local AI."
    echo "   Then set ATOM_LOCAL_ONLY=true in backend/.env"
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Edit backend/.env — add an API key or set ATOM_LOCAL_ONLY=true"
echo "  2. Run: ./scripts/dev.sh"
echo "  3. Open http://localhost:3000"
echo ""
echo "Admin password will be printed on first backend startup."
