"use client";

import React, { useState, useEffect } from "react";
import { marked } from "marked";
import { X, ExternalLink, Check, Code, Camera, Globe, Play, Layers, MessageSquare, ListTodo, ClipboardCheck, Activity } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CanvasHostProps, CanvasState } from "./types";
import { LineChartCanvas } from "./LineChart";
import { BarChartCanvas } from "./BarChart";
import { PieChartCanvas } from "./PieChart";
import { InteractiveForm } from "./InteractiveForm";
import {
  AgentOperationTracker,
  AgentRequestPrompt,
  InternProposalReview,
  SupervisedAgentMonitor
} from "./index";

import { getBackendWsUrl } from "@/lib/api/ws-util";

/**
 * CanvasHost - Multi-tenant real-time canvas host
 *
 * Ported from upstream with:
 * - Tenant context awareness (tenantId required)
 * - WebSocket support for real-time updates
 * - Multi-component rendering (charts, forms, markdown, etc.)
 * - Governance integration (optional agentId)
 * - Canvas state management
 */
export function CanvasHost({
  tenantId,
  agentId,
  lastMessage,
}: CanvasHostProps) {
  const [state, setState] = useState<CanvasState | null>(null);
  const [canvasId] = useState(
    () => `canvas_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
  );
  const [ws, setWs] = useState<WebSocket | null>(null);

  // WebSocket connection for real-time canvas updates
  useEffect(() => {
    if (!tenantId) return;

    // Build WebSocket URL with tenant authentication
    const wsUrl = getBackendWsUrl(`/api/feed/ws?tenantId=${tenantId}${agentId ? `&agentId=${agentId}` : ""}`);

    try {
      const websocket = new WebSocket(wsUrl);

      websocket.onopen = () => {
        console.log("[CanvasHost] WebSocket connected");
      };

      websocket.onmessage = (event) => {
        try {
          const message = JSON.parse(event.data);

          // Handle canvas update messages
          if (
            message.type === "canvas:update" ||
            message.type === "canvas:present"
          ) {
            const { action, component, data, title } = message.data || message;

            if (action === "close") {
              setState(null);
            } else if (action === "present" || action === "update") {
              setState({
                visible: true,
                component: component || "markdown",
                title,
                data,
              });
            }
          }
        } catch (err) {
          console.error("[CanvasHost] Failed to parse WebSocket message:", err);
        }
      };

      websocket.onerror = (error) => {
        console.error("[CanvasHost] WebSocket error:", error);
      };

      websocket.onclose = () => {
        console.log("[CanvasHost] WebSocket disconnected");
      };

      setWs(websocket);

      return () => {
        websocket.close();
      };
    } catch (error) {
      console.error("[CanvasHost] Failed to connect WebSocket:", error);
    }
  }, [tenantId, agentId]);

  // Handle lastMessage prop (for non-WebSocket updates)
  useEffect(() => {
    if (!lastMessage) return;

    const msg = lastMessage;

    // Support both message patterns
    if (msg.type === "canvas:update" || msg.type === "canvas:present") {
      const { action, component, data, title } = msg.data || msg;

      if (action === "close") {
        setState(null);
      } else if (action === "present" || action === "update") {
        setState({
          visible: true,
          component: component || "markdown",
          title,
          data,
        });
      }
    }
  }, [lastMessage]);

  if (!state || !state.visible) return null;

  return (
    <div className="absolute top-4 right-4 bottom-4 w-[450px] bg-background border shadow-xl z-50 rounded-lg flex flex-col animate-in slide-in-from-right-10 overflow-hidden ring-1 ring-border/50">
      <div className="flex items-center justify-between p-4 border-b bg-muted/40">
        <div className="flex items-center gap-2">
          <CanvasIcon component={state.component} />
          <h3 className="font-semibold text-sm truncate max-w-[300px]">
            {state.title || "Agent Canvas"}
          </h3>
        </div>
        <Button
          variant="ghost"
          size="icon"
          className="h-8 w-8"
          onClick={() => setState(null)}
        >
          <X className="h-4 w-4" />
        </Button>
      </div>

      <div className="flex-1 overflow-auto p-4 custom-scrollbar">
        <CanvasContent
          component={state.component}
          data={state.data}
          canvasId={canvasId}
          tenantId={tenantId}
          agentId={agentId}
        />
      </div>

      <div className="p-2 border-t bg-muted/10 text-[10px] text-muted-foreground text-center">
        Generated by Atom AI
      </div>
    </div>
  );
}

function CanvasIcon({ component }: { component: string }) {
  switch (component) {
    case "eval":
      return <Code className="h-4 w-4 text-blue-500" />;
    case "snapshot":
      return <Camera className="h-4 w-4 text-purple-500" />;
    case "browser_view":
      return <Globe className="h-4 w-4 text-green-500" />;
    case "markdown":
      return <ExternalLink className="h-4 w-4 text-primary" />;
    case "status_panel":
      return <Check className="h-4 w-4 text-green-500" />;
    case "agent_operation_tracker":
      return <ListTodo className="h-4 w-4 text-orange-500" />;
    case "agent_request_prompt":
      return <MessageSquare className="h-4 w-4 text-blue-500" />;
    case "intern_proposal_review":
      return <ClipboardCheck className="h-4 w-4 text-purple-500" />;
    case "supervised_agent_monitor":
      return <Activity className="h-4 w-4 text-red-500" />;
    default:
      return <Layers className="h-4 w-4 text-primary" />;
  }
}

interface CanvasContentProps {
  component: string;
  data: any;
  canvasId: string;
  tenantId: string;
  agentId?: string;
}

function CanvasContent({
  component,
  data,
  canvasId,
  tenantId,
  agentId,
}: CanvasContentProps) {
  if (!data) return <div className="text-muted-foreground p-4">No data to display</div>;

  switch (component) {
    case "markdown":
      return (
        <div
          className="prose dark:prose-invert max-w-none text-sm prose-p:leading-relaxed prose-pre:bg-muted"
          dangerouslySetInnerHTML={{
            __html: marked.parse(typeof data === "string" ? data : data.content || "") as string,
          }}
        />
      );

    case "eval":
      return (
        <div className="space-y-4">
          <div className="bg-zinc-950 rounded-lg p-4 font-mono text-xs overflow-auto border border-zinc-800 shadow-inner">
            <div className="flex justify-between items-center mb-2 border-b border-zinc-800 pb-2">
              <span className="text-zinc-500">javascript</span>
              <Button
                variant="ghost"
                size="sm"
                className="h-6 text-[10px] text-zinc-400 hover:text-white"
              >
                <Play className="h-3 w-3 mr-1" /> Run
              </Button>
            </div>
            <pre className="text-blue-400">{data.code || data}</pre>
          </div>
          {data.output && (
            <div className="bg-muted/50 rounded-lg p-3 border">
              <p className="text-[10px] font-bold uppercase text-muted-foreground mb-1">
                Output
              </p>
              <pre className="text-xs">
                {typeof data.output === "string"
                  ? data.output
                  : JSON.stringify(data.output, null, 2)}
              </pre>
            </div>
          )}
        </div>
      );

    case "snapshot":
      return (
        <div className="space-y-4">
          <div className="flex flex-wrap gap-2 mb-4">
            {data.timestamp && (
              <span className="px-2 py-1 rounded-md bg-muted text-[10px] text-muted-foreground border">
                Captured: {new Date(data.timestamp).toLocaleTimeString()}
              </span>
            )}
            {data.source && (
              <span className="px-2 py-1 rounded-md bg-primary/10 text-[10px] text-primary border border-primary/20">
                Source: {data.source}
              </span>
            )}
          </div>
          <div className="border rounded-lg overflow-hidden bg-card">
            <div className="p-2 border-b bg-muted/20 flex justify-between items-center">
              <span className="text-[10px] font-medium text-muted-foreground uppercase tracking-wider">
                State Tree
              </span>
            </div>
            <pre className="p-4 text-[11px] overflow-auto max-h-[400px] bg-muted/5 font-mono">
              {JSON.stringify(data.state || data, null, 2)}
            </pre>
          </div>
        </div>
      );

    case "browser_view":
      return (
        <div className="space-y-4">
          <div className="flex items-center gap-2 p-2 bg-muted/30 rounded-lg border text-xs">
            <Globe className="h-3 w-3 text-muted-foreground" />
            <span className="truncate flex-1 text-muted-foreground italic">
              {data.url || "about:blank"}
            </span>
          </div>
          {data.screenshot ? (
            <div className="border rounded-lg overflow-hidden shadow-sm relative group">
              <img
                src={
                  data.screenshot.startsWith("data:")
                    ? data.screenshot
                    : `data:image/png;base64,${data.screenshot}`
                }
                alt="Browser Snapshot"
                className="w-full h-auto cursor-zoom-in"
              />
              <div className="absolute inset-x-0 bottom-0 bg-black/60 backdrop-blur-sm p-2 opacity-0 group-hover:opacity-100 transition-opacity">
                <p className="text-[10px] text-white text-center">
                  Interactive remote control disabled in preview
                </p>
              </div>
            </div>
          ) : (
            <div className="h-[300px] border border-dashed rounded-lg flex flex-col items-center justify-center text-muted-foreground">
              <Globe className="h-8 w-8 mb-2 opacity-20" />
              <p className="text-xs">Connecting to remote browser...</p>
            </div>
          )}
        </div>
      );

    case "status_panel":
      return (
        <div className="space-y-4">
          {data.items?.map((item: any, i: number) => (
            <div key={i} className="bg-card/50 border rounded-lg p-4 flex items-center justify-between">
              <span className="text-sm font-medium">{item.label}</span>
              <div className="flex items-center gap-2">
                <span className="text-lg font-bold">{item.value}</span>
                {item.trend && (
                  <span
                    className={`text-xs ${item.trend > 0 ? "text-green-500" : "text-red-500"
                      }`}
                  >
                    {item.trend > 0 ? "↑" : "↓"} {Math.abs(item.trend)}%
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      );

    case "form":
      return (
        <InteractiveForm
          tenantId={tenantId}
          agentId={agentId}
          fields={data.fields}
          title={data.title}
          submitLabel={data.submitLabel}
          canvasId={canvasId}
          onSubmit={async (formData) => {
            try {
              const response = await fetch("/api/canvas/forms/submit", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                  tenantId,
                  agentId,
                  canvasId,
                  formData,
                }),
              });

              if (!response.ok) {
                throw new Error("Submission failed");
              }

              const result = await response.json();
              if (!result.success) {
                throw new Error(result.error || "Submission failed");
              }
            } catch (error) {
              console.error("Form submission error:", error);
              throw error;
            }
          }}
        />
      );

    case "line_chart":
      return (
        <LineChartCanvas
          tenantId={tenantId}
          agentId={agentId}
          data={data.data}
          title={data.title}
          color={data.color}
        />
      );

    case "bar_chart":
      return (
        <BarChartCanvas
          tenantId={tenantId}
          agentId={agentId}
          data={data.data}
          title={data.title}
          color={data.color}
        />
      );

    case "pie_chart":
      return (
        <PieChartCanvas
          tenantId={tenantId}
          agentId={agentId}
          data={data.data}
          title={data.title}
        />
      );

    case "agent_operation_tracker":
      return (
        <AgentOperationTracker
          agentId={agentId || data.agent_id}
          tenantId={tenantId}
          initialData={data}
        />
      );

    case "agent_request_prompt":
      return (
        <AgentRequestPrompt
          request={data}
          onRespond={async (requestId, action) => {
            console.log(`Responding to ${requestId} with ${action}`);
            // Logic to send response to backend
            const response = await fetch(`/api/proposals/${requestId}/respond`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'X-Tenant-ID': tenantId
              },
              body: JSON.stringify({ action })
            });
            if (!response.ok) throw new Error('Failed to respond');
          }}
        />
      );

    case "intern_proposal_review":
      return (
        <InternProposalReview
          proposalId={data.proposal_id || data.id}
          onComplete={() => { }}
        />
      );

    case "supervised_agent_monitor":
      return (
        <SupervisedAgentMonitor
          agentId={agentId || data.agent_id}
          executionId={data.execution_id}
        />
      );

    default:
      return (
        <div className="p-4 border rounded-md border-dashed">
          <p className="text-sm font-medium mb-2">Component: {component}</p>
          <pre className="text-xs overflow-auto bg-muted p-2 rounded">
            {JSON.stringify(data, null, 2)}
          </pre>
        </div>
      );
  }
}
