// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type PageRoutes = never
type LayoutRoutes = never
type RedirectRoutes = never
type RewriteRoutes = "/api/accounting/[[...path]]" | "/api/admin" | "/api/admin/[[...path]]" | "/api/agents" | "/api/agents/" | "/api/agents/[[...path]]" | "/api/ai/[[...path]]" | "/api/analytics/[[...path]]" | "/api/atom-agent/[[...path]]" | "/api/atom/[[...path]]" | "/api/auth/[service]/authorize" | "/api/auth/[service]/disconnect" | "/api/auth/[service]/initiate" | "/api/auth/[service]/status" | "/api/auth/accounts" | "/api/auth/change-password" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/profile" | "/api/auth/refresh" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/verify-token" | "/api/boards/[[...path]]" | "/api/business-health/[[...path]]" | "/api/chat/[[...path]]" | "/api/data-ingestion/[[...path]]" | "/api/documents" | "/api/documents/[[...path]]" | "/api/dropbox/[[...path]]" | "/api/episodes" | "/api/episodes/[[...path]]" | "/api/gdrive/[[...path]]" | "/api/gitlab/[[...path]]" | "/api/ingest-gdrive-document" | "/api/integrations/[[...path]]" | "/api/intelligence/[[...path]]" | "/api/marketing" | "/api/marketing/[[...path]]" | "/api/maturity" | "/api/maturity/[[...path]]" | "/api/memory/[[...path]]" | "/api/monday/[[...path]]" | "/api/onboarding/[[...path]]" | "/api/onedrive/[[...path]]" | "/api/sales/[[...path]]" | "/api/shopify/[[...path]]" | "/api/system/[[...path]]" | "/api/telegram/[[...path]]" | "/api/time-travel/[[...path]]" | "/api/users/[[...path]]" | "/api/v1/[[...path]]" | "/api/v1/auth/oauth/[[...path]]" | "/api/v1/employee/[[...path]]" | "/api/whatsapp/[[...path]]" | "/api/workflow-agent/[[...path]]" | "/api/workflow-templates" | "/api/workflow-templates/[[...path]]" | "/api/workflows/[[...path]]" | "/api/xero/[[...path]]" | "/api/zoho-workdrive/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/api/accounting/[[...path]]": { "path"?: string[]; }
  "/api/admin": {}
  "/api/admin/[[...path]]": { "path"?: string[]; }
  "/api/agents": {}
  "/api/agents/": {}
  "/api/agents/[[...path]]": { "path"?: string[]; }
  "/api/ai/[[...path]]": { "path"?: string[]; }
  "/api/analytics/[[...path]]": { "path"?: string[]; }
  "/api/atom-agent/[[...path]]": { "path"?: string[]; }
  "/api/atom/[[...path]]": { "path"?: string[]; }
  "/api/auth/[service]/authorize": { "service": string; }
  "/api/auth/[service]/disconnect": { "service": string; }
  "/api/auth/[service]/initiate": { "service": string; }
  "/api/auth/[service]/status": { "service": string; }
  "/api/auth/accounts": {}
  "/api/auth/change-password": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/profile": {}
  "/api/auth/refresh": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify-token": {}
  "/api/boards/[[...path]]": { "path"?: string[]; }
  "/api/business-health/[[...path]]": { "path"?: string[]; }
  "/api/chat/[[...path]]": { "path"?: string[]; }
  "/api/data-ingestion/[[...path]]": { "path"?: string[]; }
  "/api/documents": {}
  "/api/documents/[[...path]]": { "path"?: string[]; }
  "/api/dropbox/[[...path]]": { "path"?: string[]; }
  "/api/episodes": {}
  "/api/episodes/[[...path]]": { "path"?: string[]; }
  "/api/gdrive/[[...path]]": { "path"?: string[]; }
  "/api/gitlab/[[...path]]": { "path"?: string[]; }
  "/api/ingest-gdrive-document": {}
  "/api/integrations/[[...path]]": { "path"?: string[]; }
  "/api/intelligence/[[...path]]": { "path"?: string[]; }
  "/api/marketing": {}
  "/api/marketing/[[...path]]": { "path"?: string[]; }
  "/api/maturity": {}
  "/api/maturity/[[...path]]": { "path"?: string[]; }
  "/api/memory/[[...path]]": { "path"?: string[]; }
  "/api/monday/[[...path]]": { "path"?: string[]; }
  "/api/onboarding/[[...path]]": { "path"?: string[]; }
  "/api/onedrive/[[...path]]": { "path"?: string[]; }
  "/api/sales/[[...path]]": { "path"?: string[]; }
  "/api/shopify/[[...path]]": { "path"?: string[]; }
  "/api/system/[[...path]]": { "path"?: string[]; }
  "/api/telegram/[[...path]]": { "path"?: string[]; }
  "/api/time-travel/[[...path]]": { "path"?: string[]; }
  "/api/users/[[...path]]": { "path"?: string[]; }
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/api/v1/auth/oauth/[[...path]]": { "path"?: string[]; }
  "/api/v1/employee/[[...path]]": { "path"?: string[]; }
  "/api/whatsapp/[[...path]]": { "path"?: string[]; }
  "/api/workflow-agent/[[...path]]": { "path"?: string[]; }
  "/api/workflow-templates": {}
  "/api/workflow-templates/[[...path]]": { "path"?: string[]; }
  "/api/workflows/[[...path]]": { "path"?: string[]; }
  "/api/xero/[[...path]]": { "path"?: string[]; }
  "/api/zoho-workdrive/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
