#!/bin/bash

# Atom Personal Edition - Native Installation Script
# This script automates the native installation process for macOS/Linux
# Run with: ./install-native.sh

set -e  # Exit on error

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Atom Personal Edition - Native Installation              ║"
echo "║  AI Automation Platform on Your Local Computer            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check prerequisites
echo "🔍 Checking prerequisites..."

# Check Python
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is not installed. Please install Python 3.11 or higher."
    echo "   macOS: brew install python@3.11"
    echo "   Ubuntu: sudo apt install python3.11"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | awk '{print $2}')
echo "✅ Python found: $PYTHON_VERSION"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js 18 or higher."
    echo "   macOS: brew install node"
    echo "   Ubuntu: sudo apt install nodejs npm"
    exit 1
fi

NODE_VERSION=$(node --version)
echo "✅ Node.js found: $NODE_VERSION"

# Check npm
if ! command -v npm &> /dev/null; then
    echo "❌ npm is not installed."
    exit 1
fi

NPM_VERSION=$(npm --version)
echo "✅ npm found: $NPM_VERSION"

# Check Git
if ! command -v git &> /dev/null; then
    echo "❌ Git is not installed. Please install Git."
    echo "   macOS: brew install git"
    echo "   Ubuntu: sudo apt install git"
    exit 1
fi

GIT_VERSION=$(git --version)
echo "✅ Git found: $GIT_VERSION"

echo ""
echo "✅ All prerequisites satisfied!"
echo ""

# Backend setup
echo "📦 Setting up backend..."
cd backend

# Create virtual environment
if [ ! -d "venv" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv venv
fi

# Activate virtual environment
echo "Activating virtual environment..."
source venv/bin/activate

# Upgrade pip
echo "Upgrading pip..."
pip install --upgrade pip --quiet

# Install dependencies
echo "Installing Python dependencies..."
pip install -r requirements.txt --quiet

echo "✅ Backend setup complete!"
echo ""

# Frontend setup
echo "📦 Setting up frontend..."
cd ../frontend-nextjs

# Install dependencies
if [ ! -d "node_modules" ]; then
    echo "Installing Node.js dependencies..."
    npm install --silent
fi

echo "✅ Frontend setup complete!"
echo ""

# Environment configuration
echo "⚙️  Configuring environment..."
cd ..

if [ ! -f ".env" ]; then
    if [ -f ".env.personal" ]; then
        echo "Copying .env.personal to .env..."
        cp .env.personal .env
    else
        echo "Creating .env file..."
        cat > .env << EOF
# Atom Personal Edition - Environment Configuration
# Generated by install-native.sh

# AI Provider API Keys (REQUIRED - at least one)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# Encryption Keys (REQUIRED - generate with: openssl rand -base64 32)
BYOK_ENCRYPTION_KEY=
JWT_SECRET_KEY=

# Database (DATABASE_URL — the app reads this; a relative sqlite path
# is anchored to backend/ by the app itself)
DATABASE_URL=sqlite:///./data/atom.db
LANCEDB_PATH=./data/lancedb

# Environment
ENVIRONMENT=development
LOG_LEVEL=INFO
EOF
    fi
fi

# Encryption keys: generate ONLY what is missing. A rerun must NEVER
# regenerate configured secrets — a rotated BYOK_ENCRYPTION_KEY makes
# every stored credential undecryptable, and a rotated JWT_SECRET_KEY
# invalidates every issued session (owner correction 2026-10-08).
echo ""
echo "🔐 Checking encryption keys..."
set_env_key() {
    # set_env_key <VAR> <value> — replace or append in .env
    if grep -q "^${1}=" .env 2>/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^${1}=.*|${1}=${2}|" .env
        else
            sed -i "s|^${1}=.*|${1}=${2}|" .env
        fi
    else
        echo "${1}=${2}" >> .env
    fi
}
if grep -q "^BYOK_ENCRYPTION_KEY=..*" .env 2>/dev/null; then
    echo "   BYOK_ENCRYPTION_KEY already configured — preserved"
else
    set_env_key BYOK_ENCRYPTION_KEY "$(openssl rand -base64 32)"
    echo "   BYOK_ENCRYPTION_KEY generated"
fi
if grep -q "^JWT_SECRET_KEY=..*" .env 2>/dev/null; then
    echo "   JWT_SECRET_KEY already configured — preserved"
else
    set_env_key JWT_SECRET_KEY "$(openssl rand -base64 32)"
    echo "   JWT_SECRET_KEY generated"
fi
echo "✅ Encryption keys verified"
echo ""

# Create data directory
echo "📁 Creating data directory..."
mkdir -p data
echo "✅ Data directory created: ./data"
echo ""

# Initialize the database schema.
# 2026-10-08 fresh-install repair: `alembic upgrade head` FAILS on a
# fresh checkout — the tree carries six unmerged branch heads and the
# branches have cross-branch ALTER/CREATE dependencies, so no ordering
# can build an empty database (verified on an isolated clean install).
# The app's own startup path is the schema authority for fresh
# databases (main_api_app: create_all + sqlite drift repair — the same
# code every boot runs). The installer therefore initializes via that
# path and ADOPTS the schema with alembic's supported `stamp heads`, so
# later incremental migrations apply normally. Heads are NOT merged and
# create_all is not substituted for upgrades on existing databases.
# Fresh-schema adoption ONLY for a verified EMPTY database. An existing
# database must go through the validated alembic upgrade path (or stop
# with an actionable message) — silently stamping an existing database
# "current" would mask real drift (owner correction 2026-10-08).
echo "🗄️  Initializing database schema..."
cd backend
source venv/bin/activate
DB_STATE=$(python - <<'PYSTATE'
import sys
from sqlalchemy import inspect
from core.database import engine
tables = set(inspect(engine).get_table_names())
if not tables:
    print("EMPTY")
elif "alembic_version" in tables:
    print("MANAGED")
else:
    print("UNMANAGED")
PYSTATE
)
case "$DB_STATE" in
    EMPTY)
        python -c "from core.database import engine; from core.models import Base; Base.metadata.create_all(engine); print('schema created')"
        alembic stamp heads
        echo "✅ Fresh database initialized (schema created, migration state stamped)"
        ;;
    MANAGED)
        echo "   Existing database with migration history — applying validated upgrades..."
        alembic upgrade heads || {
            echo "❌ Upgrade failed. Database left untouched by this installer step."
            echo "   Inspect backend/alembic history and resolve the failing migration"
            echo "   before retrying; do NOT run 'alembic stamp' by hand."
            exit 1
        }
        echo "✅ Existing database upgraded"
        ;;
    UNMANAGED)
        echo "❌ Existing database WITHOUT migration history (no alembic_version table)."
        echo "   Refusing to stamp it current — that would mask unknown drift."
        echo "   Back it up, then either import into a fresh install or add a"
        echo "   baseline alembic revision matching its actual schema."
        exit 1
        ;;
esac
echo ""

cd ..

# Summary
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅ Installation Complete!                                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Add your AI provider API keys to .env:"
echo "   nano .env"
echo ""
echo "   Set at least one of:"
echo "   - OPENAI_API_KEY=sk-your-key-here"
echo "   - ANTHROPIC_API_KEY=sk-ant-your-key-here"
echo ""
echo "2. Start Atom:"
echo ""
echo "   Terminal 1 (Backend):"
echo "   cd backend"
echo "   source venv/bin/activate"
echo "   python -m uvicorn main_api_app:app --host 0.0.0.0 --port 8000 --reload"
echo ""
echo "   Terminal 2 (Frontend):"
echo "   cd frontend-nextjs"
echo "   npm run dev"
echo ""
echo "3. Access Atom:"
echo "   🌐 Frontend: http://localhost:3000"
echo "   🔌 Backend API: http://localhost:8000"
echo "   📚 API Docs: http://localhost:8000/docs"
echo ""
echo "📚 Documentation:"
echo "   - Personal Edition Guide: docs/PERSONAL_EDITION.md"
echo "   - Native Setup Guide: docs/NATIVE_SETUP.md"
echo "   - Full Documentation: docs/README.md"
echo ""
echo "🚀 Happy automating!"
echo ""
